"""
Auto-generated Generator Registry for PyInstaller

This file explicitly imports all generator classes so PyInstaller
can detect and include them in the executable.

DO NOT EDIT MANUALLY - Run build_generator_registry.py to regenerate.
"""

# Generator imports
from generators.High_School.Algebra.Unit_1.combining_like_terms_generator import CombiningLikeTermsGenerator
from generators.High_School.Algebra.Unit_1.dependent_and_independent_variables_generator import DependentAndIndependentVariablesGenerator
from generators.High_School.Algebra.Unit_1.evaluating_expressions_generator import EvaluatingExpressionsGenerator
from generators.High_School.Algebra.Unit_1.evaluating_expressions_with_exponents_greater_than_1_generator import EvaluatingExpressionsWithExponentsGreaterThan1Generator
from generators.High_School.Algebra.Unit_1.evaluating_expressions_with_multiple_terms_generator import EvaluatingExpressionsWithMultipleTermsGenerator
from generators.High_School.Algebra.Unit_1.evaluating_expressions_with_multiple_variables_generator import EvaluatingExpressionsWithMultipleVariablesGenerator
from generators.High_School.Algebra.Unit_1.expanding_and_simplifying_expressions_with_exponents_generator import ExpandingAndSimplifyingExpressionsWithExponentsGenerator
from generators.High_School.Algebra.Unit_1.expanding_and_simplifying_variables_with_exponents_generator import ExpandingAndSimplifyingVariablesWithExponentsGenerator
from generators.High_School.Algebra.Unit_1.expanding_exponents_generator import ExpandingExponentsGenerator
from generators.High_School.Algebra.Unit_1.exponents_generator import ExponentsGenerator
from generators.High_School.Algebra.Unit_1.exponents_properties_generator import ExponentsPropertiesGenerator
from generators.High_School.Algebra.Unit_1.multiple_terms_in_a_single_expression_generator import MultipleTermsInASingleExpressionGenerator
from generators.High_School.Algebra.Unit_1.parts_of_a_term_recognizing_that_coefficients_are_multiplication_generator import PartsOfATermRecognizingThatCoefficientsAreMultiplicationGenerator
from generators.High_School.Algebra.Unit_1.parts_of_term_exponents_review_generator import PartsOfTermExponentsReviewGenerator
from generators.High_School.Algebra.Unit_1.properties_of_exponents_generator import PropertiesOfExponentsGenerator
from generators.High_School.Algebra.Unit_1.substitution_generator import SubstitutionGenerator
from generators.High_School.Algebra.Unit_1.variables_both_sides_generator import VariablesBothSidesGenerator
from generators.High_School.Algebra.Unit_1.variables_generator import VariablesGenerator
from generators.High_School.Algebra.Unit_1.writing_expression_word_problems_generator import WritingExpressionWordProblemsGenerator
from generators.High_School.Algebra.Unit_10.functions_what_is_the_point_vs_an_equation_function_notation_generator import FunctionsWhatIsThePointVsAnEquationFunctionNotationGenerator
from generators.High_School.Algebra.Unit_10.quadratic_graphing_generator import QuadraticGraphingGenerator
from generators.High_School.Algebra.Unit_10.quadratics_by_factoring_generator import QuadraticsByFactoringGenerator
from generators.High_School.Algebra.Unit_10.solving_quadratics_by_factoring_factor_for_the_roots_use_xp_over_2_to_find_vertex_generator import SolvingQuadraticsByFactoringFactorForTheRootsUseXPlusPOver2ToFindVertexGenerator
from generators.High_School.Algebra.Unit_10.vertex_form_generator import VertexFormGenerator
from generators.High_School.Algebra.Unit_11.completing_the_square_generator import CompletingTheSquareGenerator
from generators.High_School.Algebra.Unit_11.quadratic_formula_hard_to_use_the_three_main_methods_and_completing_the_square_generator import QuadraticFormulaHardToUseTheThreeMainMethodsAndCompletingTheSquareGenerator
from generators.High_School.Algebra.Unit_12.interpreting_quadratic_functions_word_problems_generator import InterpretingQuadraticFunctionsWordProblemsGenerator
from generators.High_School.Algebra.Unit_12.quadratic_functions_generator import QuadraticFunctionsGenerator
from generators.High_School.Algebra.Unit_12.quadratic_inequalities_generator import QuadraticInequalitiesGenerator
from generators.High_School.Algebra.Unit_12.writing_quadratic_functions_generator import WritingQuadraticFunctionsGenerator
from generators.High_School.Algebra.Unit_13.absolute_value_generator import AbsoluteValueGenerator
from generators.High_School.Algebra.Unit_13.absolute_value_inequalities_generator import AbsoluteValueInequalitiesGenerator
from generators.High_School.Algebra.Unit_13.constructing_geometric_sequences_generator import ConstructingGeometricSequencesGenerator
from generators.High_School.Algebra.Unit_13.modeling_with_sequences_generator import ModelingWithSequencesGenerator
from generators.High_School.Algebra.Unit_2.equations_intro_generator import EquationsIntroGenerator
from generators.High_School.Algebra.Unit_2.inputs_outputs_generator import InputsOutputsGenerator
from generators.High_School.Algebra.Unit_2.linear_equation_word_problems_generator import LinearEquationWordProblemsGenerator
from generators.High_School.Algebra.Unit_2.linear_equations_generator import LinearEquationsGenerator
from generators.High_School.Algebra.Unit_2.literal_equations_generator import LiteralEquationsGenerator
from generators.High_School.Algebra.Unit_2.property_equality_add_sub_generator import PropertyEqualityAddSubGenerator
from generators.High_School.Algebra.Unit_2.property_equality_mult_div_generator import PropertyEqualityMultDivGenerator
from generators.High_School.Algebra.Unit_2.quadratic_equations_generator import QuadraticEquationsGenerator
from generators.High_School.Algebra.Unit_2.quadratic_equations_parabola_generator import QuadraticEquationsParabolaGenerator
from generators.High_School.Algebra.Unit_2.solutions_generator import SolutionsGenerator
from generators.High_School.Algebra.Unit_2.solving_quadratic_equations_using_square_roots_no_other_terms_except_x_squared_generator import SolvingQuadraticEquationsUsingSquareRootsNoOtherTermsExceptXSquaredGenerator
from generators.High_School.Algebra.Unit_2.systems_of_equations_using_elimination_generator import SystemsOfEquationsUsingEliminationGenerator
from generators.High_School.Algebra.Unit_2.systems_of_equations_using_substitution_generator import SystemsOfEquationsUsingSubstitutionGenerator
from generators.High_School.Algebra.Unit_2.systems_of_quadratic_equations_generator import SystemsOfQuadraticEquationsGenerator
from generators.High_School.Algebra.Unit_2.two_step_equations_generator import TwoStepEquationsGenerator
from generators.High_School.Algebra.Unit_2.two_variable_linear_equations_generator import TwoVariableLinearEquationsGenerator
from generators.High_School.Algebra.Unit_2.writing_point_slope_form_equations_generator import WritingPointSlopeFormEquationsGenerator
from generators.High_School.Algebra.Unit_2.writing_slope_intercept_equations_generator import WritingSlopeInterceptEquationsGenerator
from generators.High_School.Algebra.Unit_3.compound_inequalities_generator import CompoundInequalityGenerator
from generators.High_School.Algebra.Unit_3.compound_inequality_word_problems_generator import CompoundInequalityWordProblemsGenerator
from generators.High_School.Algebra.Unit_3.inequalities_generator import InequalitiesGenerator
from generators.High_School.Algebra.Unit_3.inequality_word_problems_generator import InequalityWordProblemsGenerator
from generators.High_School.Algebra.Unit_3.multi_step_inequalities_generator import MultiStepInequalitiesGenerator
from generators.High_School.Algebra.Unit_3.simple_inequalities_generator import SimpleInequalitiesGenerator
from generators.High_School.Algebra.Unit_3.systems_of_inequalities_generator import SystemsOfInequalitiesGenerator
from generators.High_School.Algebra.Unit_3.systems_of_quadratic_inequalities_generator import SystemsOfQuadraticInequalitiesGenerator
from generators.High_School.Algebra.Unit_3.two_step_inequalities_generator import TwoStepInequalitiesGenerator
from generators.High_School.Algebra.Unit_3.writing_systems_of_inequalities_generator import WritingSystemsOfInequalitiesGenerator
from generators.High_School.Algebra.Unit_4.inputs_outputs_review_generator import InputsOutputsReviewGenerator
from generators.High_School.Algebra.Unit_4.intercepts_generator import InterceptsGenerator
from generators.High_School.Algebra.Unit_4.slope_generator import SlopeGenerator
from generators.High_School.Algebra.Unit_4.standard_form_of_quadratics_generator import StandardFormOfQuadraticsGenerator
from generators.High_School.Algebra.Unit_4.the_coordinate_plane_generator import TheCoordinatePlaneGenerator
from generators.High_School.Algebra.Unit_4.using_standard_form_b_over_2a_plus_solve_for_when_x_equals_0_generator import UsingStandardFormBOver2aPlusSolveForWhenXEquals0Generator
from generators.High_School.Algebra.Unit_4.writing_standard_form_equations_generator import WritingStandardFormEquationsGenerator
from generators.High_School.Algebra.Unit_4.x_and_y_intercepts_generator import XAndYInterceptsGenerator
from generators.High_School.Algebra.Unit_5.writing_systems_of_equation_word_problems_generator import WritingSystemsOfEquationWordProblemsGenerator
from generators.High_School.Algebra.Unit_6.domain_and_range_generator import DomainAndRangeGenerator
from generators.High_School.Algebra.Unit_6.domain_range_generator import DomainRangeGenerator
from generators.High_School.Algebra.Unit_6.functions_generator import FunctionsGenerator
from generators.High_School.Algebra.Unit_6.inputs_outputs_functions_review_generator import InputsOutputsFunctionsReviewGenerator
from generators.High_School.Algebra.Unit_6.interpreting_domain_and_range_generator import InterpretingDomainAndRangeGenerator
from generators.High_School.Algebra.Unit_7.advanced_properties_of_radicals_multiplication_fractions_generator import AdvancedPropertiesOfRadicalsMultiplicationFractionsGenerator
from generators.High_School.Algebra.Unit_7.exponent_properties_generator import ExponentPropertiesGenerator
from generators.High_School.Algebra.Unit_7.radical_properties_generator import RadicalPropertiesGenerator
from generators.High_School.Algebra.Unit_7.square_roots_generator import SquareRootsGenerator
from generators.High_School.Algebra.Unit_8.equivalent_exponential_review_generator import EquivalentExponentialReviewGenerator
from generators.High_School.Algebra.Unit_8.exponential_decay_generator import ExponentialDecayGenerator
from generators.High_School.Algebra.Unit_8.exponential_functions_generator import ExponentialFunctionsGenerator
from generators.High_School.Algebra.Unit_8.exponential_functions_using_tables_generator import ExponentialFunctionsUsingTablesGenerator
from generators.High_School.Algebra.Unit_8.exponential_growth_decay_generator import ExponentialGrowthDecayGenerator
from generators.High_School.Algebra.Unit_8.exponential_growth_generator import ExponentialGrowthGenerator
from generators.High_School.Algebra.Unit_8.linear_vs_exponential_growth_generator import LinearVsExponentialGrowthGenerator
from generators.High_School.Algebra.Unit_8.modeling_exponential_functions_generator import ModelingExponentialFunctionsGenerator
from generators.High_School.Algebra.Unit_8.writing_exponential_functions_generator import WritingExponentialFunctionsGenerator
from generators.High_School.Algebra.Unit_9.add_and_subtract_polynomials_generator import AddAndSubtractPolynomialsGenerator
from generators.High_School.Algebra.Unit_9.factor_by_grouping_generator import FactorByGroupingGenerator
from generators.High_School.Algebra.Unit_9.factoring_generator import FactoringGenerator
from generators.High_School.Algebra.Unit_9.factoring_monomials_generator import FactoringMonomialsGenerator
from generators.High_School.Algebra.Unit_9.factoring_polynomials_with_common_factors_generator import FactoringPolynomialsWithCommonFactorsGenerator
from generators.High_School.Algebra.Unit_9.multi_step_inequality_word_problems_generator import MultiStepInequalityWordProblemsGenerator
from generators.High_School.Algebra.Unit_9.multiplying_monomials_1x1_generator import MultiplyingMonomials1x1Generator
from generators.High_School.Algebra.Unit_9.multiplying_monomials_and_binomials_1x2_generator import MultiplyingMonomialsAndBinomials1x2Generator
from generators.High_School.Algebra.Unit_9.multiplying_polynomials_2x2_2x3_etc_generator import MultiplyingPolynomials2x22x3EtcGenerator
from generators.High_School.Algebra.Unit_9.parts_of_term_generator import PartsOfTermGenerator
from generators.High_School.Algebra.Unit_9.polynomial_operations_generator import PolynomialOperationsGenerator
from generators.High_School.Algebra.Unit_9.to_factor_using_perfect_squares_generator import ToFactorUsingPerfectSquaresGenerator
from generators.High_School.Algebra.number_properties_generator import NumberPropertiesGenerator
from generators.High_School.Algebra.order_of_operations_generator import OrderOfOperationsGenerator
from generators.K_8.Grade_1.Unit01.counting_and_numbers_generator import CountingAndNumbersGenerator
from generators.K_8.Grade_1.Unit01.even_and_odd_numbers_generator import EvenAndOddNumbersGenerator
from generators.K_8.Grade_1.Unit01.skip_counting_generator import SkipCountingGenerator
from generators.K_8.Grade_1.Unit02.addition_strategies_up_to_10_generator import AdditionStrategiesUpTo10Generator
from generators.K_8.Grade_1.Unit02.addition_up_to_10_generator import AdditionUpTo10Generator
from generators.K_8.Grade_1.Unit02.addition_word_problems_up_to_10_generator import AdditionWordProblemsUpTo10Generator
from generators.K_8.Grade_1.Unit02.understand_addition_generator import UnderstandAdditionGenerator
from generators.K_8.Grade_1.Unit03.subtraction_strategies_up_to_10_generator import SubtractionStrategiesUpTo10Generator
from generators.K_8.Grade_1.Unit03.subtraction_up_to_10_generator import SubtractionUpTo10Generator
from generators.K_8.Grade_1.Unit03.subtraction_word_problems_up_to_10_generator import SubtractionWordProblemsUpTo10Generator
from generators.K_8.Grade_1.Unit03.understand_subtraction_generator import UnderstandSubtractionGenerator
from generators.K_8.Grade_1.Unit04.addition_strategies_up_to_20_generator import AdditionStrategiesUpTo20Generator
from generators.K_8.Grade_1.Unit04.addition_up_to_20_generator import AdditionUpTo20Generator
from generators.K_8.Grade_1.Unit04.addition_word_problems_up_to_20_generator import AdditionWordProblemsUpTo20Generator
from generators.K_8.Grade_1.Unit05.addition_and_subtraction_up_to_20_generator import AdditionAndSubtractionUpTo20Generator
from generators.K_8.Grade_1.Unit05.subtraction_strategies_up_to_20_generator import SubtractionStrategiesUpTo20Generator
from generators.K_8.Grade_1.Unit05.subtraction_up_to_20_generator import SubtractionUpTo20Generator
from generators.K_8.Grade_1.Unit05.subtraction_word_problems_up_to_20_generator import SubtractionWordProblemsUpTo20Generator
from generators.K_8.Grade_1.Unit06.comparing_numbers_generator import ComparingNumbersGenerator
from generators.K_8.Grade_1.Unit06.ordering_numbers_generator import OrderingNumbersGenerator
from generators.K_8.Grade_1.Unit06.place_value_tens_and_ones_generator import PlaceValueTensAndOnesGenerator
from generators.K_8.Grade_1.Unit07.addition_and_subtraction_with_two_digits_generator import AdditionAndSubtractionWithTwoDigitsGenerator
from generators.K_8.Grade_1.Unit07.addition_with_two_digits_generator import AdditionWithTwoDigitsGenerator
from generators.K_8.Grade_1.Unit07.subtraction_with_two_digits_generator import SubtractionWithTwoDigitsGenerator
from generators.K_8.Grade_1.Unit08.area_introduction_generator import AreaIntroductionGenerator
from generators.K_8.Grade_1.Unit08.comparing_lengths_generator import ComparingLengthsGenerator
from generators.K_8.Grade_1.Unit08.counting_unit_squares_generator import CountingUnitSquaresGenerator
from generators.K_8.Grade_1.Unit08.measuring_with_non_standard_units_generator import MeasuringWithNonStandardUnitsGenerator
from generators.K_8.Grade_1.Unit09.coin_recognition_generator import CoinRecognitionGenerator
from generators.K_8.Grade_1.Unit09.counting_coins_generator import CountingCoinsGenerator
from generators.K_8.Grade_1.Unit09.days_months_and_seasons_generator import DaysMonthsAndSeasonsGenerator
from generators.K_8.Grade_1.Unit09.telling_time_hour_half_hour_generator import TellingTimeHourHalfHourGenerator
from generators.K_8.Grade_1.Unit10.comparing_2d_shapes_generator import Comparing2dShapesGenerator
from generators.K_8.Grade_1.Unit10.extending_patterns_generator import ExtendingPatternsGenerator
from generators.K_8.Grade_1.Unit10.identifying_2d_shapes_generator import Identifying2dShapesGenerator
from generators.K_8.Grade_1.Unit10.reading_bar_graphs_generator import ReadingBarGraphsGenerator
from generators.K_8.Grade_1.Unit10.reading_picture_graphs_generator import ReadingPictureGraphsGenerator
from generators.K_8.Grade_1.Unit10.recognizing_patterns_generator import RecognizingPatternsGenerator
from generators.K_8.Grade_2.Unit01.add_and_subtract_within_20_generator import AddAndSubtractWithin20Generator
from generators.K_8.Grade_2.Unit01.add_using_arrays_generator import AddUsingArraysGenerator
from generators.K_8.Grade_2.Unit01.add_within_20_generator import AddWithin20Generator
from generators.K_8.Grade_2.Unit01.subtract_within_20_generator import SubtractWithin20Generator
from generators.K_8.Grade_2.Unit02.comparing_2_and_3_digit_numbers_generator import Comparing2And3DigitNumbersGenerator
from generators.K_8.Grade_2.Unit02.counting_patterns_within_1000_generator import CountingPatternsWithin1000Generator
from generators.K_8.Grade_2.Unit02.even_and_odd_numbers_generator import EvenAndOddNumbersGenerator
from generators.K_8.Grade_2.Unit02.intro_to_place_value_generator import IntroToPlaceValueGenerator
from generators.K_8.Grade_2.Unit02.numbers_in_standard_word_expanded_form_generator import NumbersInStandardWordExpandedFormGenerator
from generators.K_8.Grade_2.Unit02.regroup_whole_numbers_generator import RegroupWholeNumbersGenerator
from generators.K_8.Grade_2.Unit03.add_subtract_within_100_word_problems_generator import AddSubtractWithin100WordProblemsGenerator
from generators.K_8.Grade_2.Unit03.add_subtract_within_100_word_problems_multi_step_generator import AddSubtractWithin100WordProblemsMultiStepGenerator
from generators.K_8.Grade_2.Unit03.addition_and_subtraction_missing_values_generator import AdditionAndSubtractionMissingValuesGenerator
from generators.K_8.Grade_2.Unit03.strategies_for_adding_within_100_generator import StrategiesForAddingWithin100Generator
from generators.K_8.Grade_2.Unit03.visually_adding_within_100_generator import VisuallyAddingWithin100Generator
from generators.K_8.Grade_2.Unit03.visually_subtract_within_100_generator import VisuallySubtractWithin100Generator
from generators.K_8.Grade_2.Unit04.adding_up_to_four_2_digit_numbers_generator import AddingUpToFour2DigitNumbersGenerator
from generators.K_8.Grade_2.Unit04.strategies_for_adding_within_1000_generator import StrategiesForAddingWithin1000Generator
from generators.K_8.Grade_2.Unit04.strategies_for_subtracting_within_1000_generator import StrategiesForSubtractingWithin1000Generator
from generators.K_8.Grade_2.Unit04.visually_adding_within_1000_generator import VisuallyAddingWithin1000Generator
from generators.K_8.Grade_2.Unit05.counting_money_generator import CountingMoneyGenerator
from generators.K_8.Grade_2.Unit05.time_generator import TimeGenerator
from generators.K_8.Grade_2.Unit06.estimate_lengths_generator import EstimateLengthsGenerator
from generators.K_8.Grade_2.Unit06.length_word_problems_generator import LengthWordProblemsGenerator
from generators.K_8.Grade_2.Unit06.measure_lengths_generator import MeasureLengthsGenerator
from generators.K_8.Grade_2.Unit06.units_of_length_generator import UnitsOfLengthGenerator
from generators.K_8.Grade_2.Unit07.bar_graphs_generator import BarGraphsGenerator
from generators.K_8.Grade_2.Unit07.line_plots_generator import LinePlotsGenerator
from generators.K_8.Grade_2.Unit07.picture_graphs_generator import PictureGraphsGenerator
from generators.K_8.Grade_2.Unit08.equal_parts_of_shapes_generator import EqualPartsOfShapesGenerator
from generators.K_8.Grade_2.Unit08.partition_rectangles_generator import PartitionRectanglesGenerator
from generators.K_8.Grade_2.Unit08.shapes_generator import ShapesGenerator
from generators.K_8.Grade_3.Unit01.multiplication_as_equal_groups_generator import MultiplicationAsEqualGroupsGenerator
from generators.K_8.Grade_3.Unit01.multiplication_as_groups_of_objects_generator import MultiplicationAsGroupsOfObjectsGenerator
from generators.K_8.Grade_3.Unit02.distributive_property_generator import DistributivePropertyGenerator
from generators.K_8.Grade_3.Unit02.multiply_by_0_or_1_generator import MultiplyBy0Or1Generator
from generators.K_8.Grade_3.Unit02.multiply_by_2_or_4_generator import MultiplyBy2Or4Generator
from generators.K_8.Grade_3.Unit02.multiply_by_3_or_6_generator import MultiplyBy3Or6Generator
from generators.K_8.Grade_3.Unit02.multiply_by_5_or_10_generator import MultiplyBy5Or10Generator
from generators.K_8.Grade_3.Unit02.multiply_by_7_8_or_9_generator import MultiplyBy7_8Or9Generator
from generators.K_8.Grade_3.Unit03.adding_with_regrouping_within_1000_generator import AddingWithRegroupingWithin1000Generator
from generators.K_8.Grade_3.Unit03.addition_and_subtraction_word_problems_generator import AdditionAndSubtractionWordProblemsGenerator
from generators.K_8.Grade_3.Unit03.estimate_to_add_multi_digit_numbers_generator import EstimateToAddMultiDigitNumbersGenerator
from generators.K_8.Grade_3.Unit03.estimate_to_subtract_multi_digit_numbers_generator import EstimateToSubtractMultiDigitNumbersGenerator
from generators.K_8.Grade_3.Unit03.rounding_to_nearest_10_or_100_generator import RoundingToNearest10Or100Generator
from generators.K_8.Grade_3.Unit03.subtracting_with_regrouping_within_1000_generator import SubtractingWithRegroupingWithin1000Generator
from generators.K_8.Grade_3.Unit04.divide_by_1_2_or_4_generator import DivideBy1_2_Or4Generator
from generators.K_8.Grade_3.Unit04.divide_by_3_or_6_generator import DivideBy3Or6Generator
from generators.K_8.Grade_3.Unit04.divide_by_5_or_10_generator import DivideBy5Or10Generator
from generators.K_8.Grade_3.Unit04.divide_by_7_8_or_9_generator import DivideBy7_8_Or9Generator
from generators.K_8.Grade_3.Unit04.division_intro_generator import DivisionIntroGenerator
from generators.K_8.Grade_3.Unit05.fractions_and_whole_numbers_generator import FractionsAndWholeNumbersGenerator
from generators.K_8.Grade_3.Unit05.fractions_in_contexts_generator import FractionsInContextsGenerator
from generators.K_8.Grade_3.Unit05.fractions_intro_generator import FractionsIntroGenerator
from generators.K_8.Grade_3.Unit06.comparing_fractions_generator import ComparingFractionsGenerator
from generators.K_8.Grade_3.Unit06.comparing_fractions_of_different_wholes_generator import ComparingFractionsOfDifferentWholesGenerator
from generators.K_8.Grade_3.Unit06.equivalent_fractions_generator import EquivalentFractionsGenerator
from generators.K_8.Grade_3.Unit07.associative_property_of_multiplication_generator import AssociativePropertyGenerator
from generators.K_8.Grade_3.Unit07.letters_and_symbols_in_multiplication_and_division_equations_generator import LettersAndSymbolsGenerator
from generators.K_8.Grade_3.Unit07.multiplication_and_division_word_problems_generator import MultiplicationDivisionWordProblemsGenerator
from generators.K_8.Grade_3.Unit07.multiplying_by_tens_generator import MultiplyingByTensGenerator
from generators.K_8.Grade_3.Unit08.estimation_word_problems_generator import EstimationWordProblemsGenerator
from generators.K_8.Grade_3.Unit08.one_and_two_step_word_problems_generator import OneAndTwoStepWordProblemsGenerator
from generators.K_8.Grade_3.Unit08.two_step_expressions_generator import TwoStepExpressionsGenerator
from generators.K_8.Grade_3.Unit10.area_introduction_generator import AreaIntroductionGenerator
from generators.K_8.Grade_3.Unit10.count_unit_squares_to_find_area_generator import CountUnitSquaresToFindAreaGenerator
from generators.K_8.Grade_3.Unit10.multiply_to_find_area_generator import MultiplyToFindAreaGenerator
from generators.K_8.Grade_3.Unit11.perimeter_generator import PerimeterGenerator
from generators.K_8.Grade_3.Unit11.perimeter_word_problems_generator import PerimeterWordProblemsGenerator
from generators.K_8.Grade_3.Unit12.elapsed_time_generator import ElapsedTimeGenerator
from generators.K_8.Grade_3.Unit12.telling_time_generator import TellingTimeGenerator
from generators.K_8.Grade_3.Unit13.mass_generator import MassGenerator
from generators.K_8.Grade_3.Unit13.volume_generator import VolumeGenerator
from generators.K_8.Grade_3.Unit14.bar_graphs_generator import BarGraphsGenerator
from generators.K_8.Grade_3.Unit14.line_plots_with_fractions_generator import LinePlotsWithFractionsGenerator
from generators.K_8.Grade_3.Unit14.picture_graphs_generator import PictureGraphsGenerator
from generators.K_8.Grade_4.Unit01.comparing_multi_digit_numbers_generator import ComparingMultiDigitNumbersGenerator
from generators.K_8.Grade_4.Unit01.how_10_relates_to_place_value_generator import How10RelatesToPlaceValueGenerator
from generators.K_8.Grade_4.Unit01.place_value_generator import PlaceValueGenerator
from generators.K_8.Grade_4.Unit01.regrouping_whole_numbers_generator import RegroupingWholeNumbersGenerator
from generators.K_8.Grade_4.Unit01.writing_whole_numbers_in_expanded_form_generator import WritingWholeNumbersInExpandedFormGenerator
from generators.K_8.Grade_4.Unit01.writing_whole_numbers_in_written_form_generator import WritingWholeNumbersInWrittenFormGenerator
from generators.K_8.Grade_4.Unit02.adding_multi_digit_numbers_generator import AddingMultiDigitNumbersGenerator
from generators.K_8.Grade_4.Unit02.rounding_whole_numbers_generator import RoundingWholeNumbersGenerator
from generators.K_8.Grade_4.Unit02.subtracting_multi_digit_numbers_generator import SubtractingMultiDigitNumbersGenerator
from generators.K_8.Grade_4.Unit03.comparing_with_multiplication_generator import ComparingWithMultiplicationGenerator
from generators.K_8.Grade_4.Unit03.estimate_products_generator import EstimateProductsGenerator
from generators.K_8.Grade_4.Unit03.multi_digit_multiplication_place_value_and_area_models_generator import MultiDigitMultiplicationPlaceValueAndAreaModelsGenerator
from generators.K_8.Grade_4.Unit03.multiplication_by_10s_100s_and_1000s_generator import MultiplicationBy10s100sAnd1000sGenerator
from generators.K_8.Grade_4.Unit03.multiply_with_partial_products_generator import MultiplyWithPartialProductsGenerator
from generators.K_8.Grade_4.Unit04.estimate_products_2_digit_numbers_generator import EstimateProducts2DigitNumbersGenerator
from generators.K_8.Grade_4.Unit04.multiply_2_digit_numbers_with_area_models_generator import Multiply2DigitNumbersWithAreaModelsGenerator
from generators.K_8.Grade_4.Unit04.multiply_2_digit_numbers_with_partial_products_generator import Multiply2DigitNumbersWithPartialProductsGenerator
from generators.K_8.Grade_4.Unit04.multiply_by_10s_generator import MultiplyBy10sGenerator
from generators.K_8.Grade_4.Unit05.divide_multiples_of_10_100_and_1000_by_1_digit_numbers_generator import DivideMultiplesOf10100And1000By1DigitNumbersGenerator
from generators.K_8.Grade_4.Unit05.division_with_area_models_generator import DivisionWithAreaModelsGenerator
from generators.K_8.Grade_4.Unit05.division_with_place_value_generator import DivisionWithPlaceValueGenerator
from generators.K_8.Grade_4.Unit05.estimate_quotients_generator import EstimateQuotientsGenerator
from generators.K_8.Grade_4.Unit05.multi_digit_division_with_partial_quotients_generator import MultiDigitDivisionWithPartialQuotientsGenerator
from generators.K_8.Grade_4.Unit05.multi_step_word_problems_generator import MultiStepWordProblemsGenerator
from generators.K_8.Grade_4.Unit05.multiplication_division_word_problems_generator import MultiplicationDivisionWordProblemsGenerator
from generators.K_8.Grade_4.Unit05.remainders_generator import RemaindersGenerator
from generators.K_8.Grade_4.Unit06.factors_and_multiples_generator import FactorsAndMultiplesGenerator
from generators.K_8.Grade_4.Unit06.math_patterns_generator import MathPatternsGenerator
from generators.K_8.Grade_4.Unit06.prime_and_composite_numbers_generator import PrimeAndCompositeNumbersGenerator
from generators.K_8.Grade_4.Unit07.common_denominators_generator import CommonDenominatorsGenerator
from generators.K_8.Grade_4.Unit07.comparing_fractions_with_unlike_denominators_generator import ComparingFractionsWithUnlikeDenominatorsGenerator
from generators.K_8.Grade_4.Unit07.comparing_fractions_with_unlike_denominators_visually_generator import ComparingFractionsWithUnlikeDenominatorsVisuallyGenerator
from generators.K_8.Grade_4.Unit07.equivalent_fractions_generator import EquivalentFractionsGenerator
from generators.K_8.Grade_4.Unit08.adding_and_subtracting_fractions_with_like_denominators_generator import AddingAndSubtractingFractionsWithLikeDenominatorsGenerator
from generators.K_8.Grade_4.Unit08.adding_and_subtracting_fractions_word_problems_generator import AddingAndSubtractingFractionsWordProblemsGenerator
from generators.K_8.Grade_4.Unit08.adding_and_subtracting_mixed_numbers_generator import AddingAndSubtractingMixedNumbersGenerator
from generators.K_8.Grade_4.Unit08.adding_and_subtracting_mixed_numbers_word_problems_generator import AddingAndSubtractingMixedNumbersWordProblemsGenerator
from generators.K_8.Grade_4.Unit08.decomposing_fractions_generator import DecomposingFractionsGenerator
from generators.K_8.Grade_4.Unit08.fractions_with_denominators_of_10_and_100_generator import FractionsWithDenominatorsOf10And100Generator
from generators.K_8.Grade_4.Unit08.line_plots_with_fractions_generator import LinePlotsWithFractionsGenerator
from generators.K_8.Grade_4.Unit08.mixed_numbers_generator import MixedNumbersGenerator
from generators.K_8.Grade_4.Unit09.multiplying_fractions_and_whole_numbers_visually_generator import MultiplyingFractionsAndWholeNumbersVisuallyGenerator
from generators.K_8.Grade_4.Unit09.multiplying_whole_numbers_and_fractions_generator import MultiplyingWholeNumbersAndFractionsGenerator
from generators.K_8.Grade_4.Unit09.multiplying_whole_numbers_and_fractions_word_problems_generator import MultiplyingWholeNumbersAndFractionsWordProblemsGenerator
from generators.K_8.Grade_4.Unit09.multiplying_whole_numbers_and_mixed_numbers_generator import MultiplyingWholeNumbersAndMixedNumbersGenerator
from generators.K_8.Grade_4.Unit10.common_fractions_and_decimals_generator import CommonFractionsAndDecimalsGenerator
from generators.K_8.Grade_4.Unit10.comparing_decimals_generator import ComparingDecimalsGenerator
from generators.K_8.Grade_4.Unit10.comparing_decimals_visually_generator import ComparingDecimalsVisuallyGenerator
from generators.K_8.Grade_4.Unit10.decimal_fractions_generator import DecimalFractionsGenerator
from generators.K_8.Grade_4.Unit10.decimal_fractions_greater_than_1_generator import DecimalFractionsGreaterThan1Generator
from generators.K_8.Grade_4.Unit10.decimals_in_word_form_generator import DecimalsInWordFormGenerator
from generators.K_8.Grade_4.Unit10.decimals_on_the_number_line_generator import DecimalsOnTheNumberLineGenerator
from generators.K_8.Grade_4.Unit10.regrouping_decimals_generator import RegroupingDecimalsGenerator
from generators.K_8.Grade_4.Unit10.writing_decimals_as_fractions_generator import WritingDecimalsAsFractionsGenerator
from generators.K_8.Grade_4.Unit10.writing_fractions_as_decimals_generator import WritingFractionsAsDecimalsGenerator
from generators.K_8.Grade_4.Unit11.angle_introduction_generator import AngleIntroductionGenerator
from generators.K_8.Grade_4.Unit11.classifying_geometric_shapes_generator import ClassifyingGeometricShapesGenerator
from generators.K_8.Grade_4.Unit11.classifying_triangles_generator import ClassifyingTrianglesGenerator
from generators.K_8.Grade_4.Unit11.line_of_symmetry_generator import LineOfSymmetryGenerator
from generators.K_8.Grade_4.Unit11.parallel_and_perpendicular_generator import ParallelAndPerpendicularGenerator
from generators.K_8.Grade_4.Unit11.types_of_plane_figures_generator import TypesOfPlaneFiguresGenerator
from generators.K_8.Grade_4.Unit12.decomposing_angles_generator import DecomposingAnglesGenerator
from generators.K_8.Grade_4.Unit12.measuring_angles_generator import MeasuringAnglesGenerator
from generators.K_8.Grade_4.Unit12.understanding_angle_measurement_generator import UnderstandingAngleMeasurementGenerator
from generators.K_8.Grade_4.Unit13.area_and_perimeter_generator import AreaAndPerimeterGenerator
from generators.K_8.Grade_4.Unit14.converting_units_of_length_generator import ConvertingUnitsOfLengthGenerator
from generators.K_8.Grade_4.Unit14.converting_units_of_mass_generator import ConvertingUnitsOfMassGenerator
from generators.K_8.Grade_4.Unit14.converting_units_of_time_generator import ConvertingUnitsOfTimeGenerator
from generators.K_8.Grade_4.Unit14.converting_units_of_volume_generator import ConvertingUnitsOfVolumeGenerator
from generators.K_8.Grade_4.Unit14.estimating_length_generator import EstimatingLengthGenerator
from generators.K_8.Grade_4.Unit14.estimating_mass_generator import EstimatingMassGenerator
from generators.K_8.Grade_4.Unit14.estimating_volume_generator import EstimatingVolumeGenerator
from generators.K_8.Grade_4.Unit14.time_generator import TimeGenerator
from generators.K_8.Grade_5.Unit01.comparing_decimals_generator import ComparingDecimalsGenerator
from generators.K_8.Grade_5.Unit01.decimal_place_value_intro_generator import DecimalPlaceValueIntroGenerator
from generators.K_8.Grade_5.Unit01.decimals_different_forms_generator import DecimalsDifferentFormsGenerator
from generators.K_8.Grade_5.Unit01.decimals_expanded_form_generator import DecimalsExpandedFormGenerator
from generators.K_8.Grade_5.Unit01.decimals_on_number_line_generator import DecimalsOnNumberLineGenerator
from generators.K_8.Grade_5.Unit01.decimals_written_form_generator import DecimalsWrittenFormGenerator
from generators.K_8.Grade_5.Unit01.rounding_decimals_generator import RoundingDecimalsGenerator
from generators.K_8.Grade_5.Unit02.adding_decimals_hundredths_generator import AddingDecimalsHundredthsGenerator
from generators.K_8.Grade_5.Unit02.adding_decimals_intro_generator import AddingDecimalsIntroGenerator
from generators.K_8.Grade_5.Unit02.adding_decimals_tenths_generator import AddingDecimalsTenthsGenerator
from generators.K_8.Grade_5.Unit02.common_fractions_decimals_generator import CommonFractionsDecimalsGenerator
from generators.K_8.Grade_5.Unit03.subtracting_decimals_hundredths_generator import SubtractingDecimalsHundredthsGenerator
from generators.K_8.Grade_5.Unit03.subtracting_decimals_intro_generator import SubtractingDecimalsIntroGenerator
from generators.K_8.Grade_5.Unit03.subtracting_decimals_tenths_generator import SubtractingDecimalsTenthsGenerator
from generators.K_8.Grade_5.Unit04.adding_subtracting_fractions_unlike_generator import AddingSubtractingFractionsUnlikeGenerator
from generators.K_8.Grade_5.Unit04.adding_subtracting_mixed_numbers_generator import AddingSubtractingMixedNumbersGenerator
from generators.K_8.Grade_5.Unit04.common_denominators_generator import CommonDenominatorsGenerator
from generators.K_8.Grade_5.Unit04.fractions_unlike_denominators_strategies_generator import FractionsUnlikeDenominatorsStrategiesGenerator
from generators.K_8.Grade_5.Unit04.fractions_word_problems_generator import FractionsWordProblemsGenerator
from generators.K_8.Grade_5.Unit05.multi_digit_division_estimation_generator import MultiDigitDivisionEstimationGenerator
from generators.K_8.Grade_5.Unit05.multi_digit_division_generator import MultiDigitDivisionGenerator
from generators.K_8.Grade_5.Unit05.multi_digit_multiplication_estimation_generator import MultiDigitMultiplicationEstimationGenerator
from generators.K_8.Grade_5.Unit05.multi_digit_multiplication_generator import MultiDigitMultiplicationGenerator
from generators.K_8.Grade_6.Unit01.equivalent_ratios_generator import EquivalentRatiosGenerator
from generators.K_8.Grade_6.Unit01.intro_to_ratios_generator import IntroToRatiosGenerator
from generators.K_8.Grade_6.Unit01.ratio_application_generator import RatioApplicationGenerator
from generators.K_8.Grade_6.Unit01.visualize_equivalent_ratios_generator import VisualizeEquivalentRatiosGenerator
from generators.K_8.Grade_6.Unit02.adding_and_subtracting_decimals_word_problems_generator import AddingAndSubtractingDecimalsWordProblemsGenerator
from generators.K_8.Grade_6.Unit02.adding_decimals_generator import AddingDecimalsGenerator
from generators.K_8.Grade_6.Unit02.dividing_decimals_generator import DividingDecimalsGenerator
from generators.K_8.Grade_6.Unit02.dividing_fractions_and_whole_numbers_generator import DividingFractionsAndWholeNumbersGenerator
from generators.K_8.Grade_6.Unit02.dividing_fractions_by_fractions_generator import DividingFractionsByFractionsGenerator
from generators.K_8.Grade_6.Unit02.dividing_whole_numbers_generator import DividingWholeNumbersGenerator
from generators.K_8.Grade_6.Unit02.multiplying_decimals_generator import MultiplyingDecimalsGenerator
from generators.K_8.Grade_6.Unit02.subtracting_decimals_generator import SubtractingDecimalsGenerator
from generators.K_8.Grade_6.Unit03.equivalent_representations_of_percent_problems_generator import EquivalentRepresentationsOfPercentProblemsGenerator
from generators.K_8.Grade_6.Unit03.intro_to_percents_generator import IntroToPercentsGenerator
from generators.K_8.Grade_6.Unit03.intro_to_rates_generator import IntroToRatesGenerator
from generators.K_8.Grade_6.Unit03.percent_problems_generator import PercentProblemsGenerator
from generators.K_8.Grade_6.Unit03.percent_word_problems_generator import PercentWordProblemsGenerator
from generators.K_8.Grade_6.Unit03.visualize_percents_generator import VisualizePercentsGenerator
from generators.K_8.Grade_6.Unit04.meaning_of_exponents_generator import MeaningOfExponentsGenerator
from generators.K_8.Grade_6.Unit04.more_on_order_of_operations_generator import MoreOnOrderOfOperationsGenerator
from generators.K_8.Grade_6.Unit04.order_of_operations_introduction_generator import OrderOfOperationsIntroductionGenerator
from generators.K_8.Grade_6.Unit04.powers_of_fractions_and_decimals_generator import PowersOfFractionsAndDecimalsGenerator
from generators.K_8.Grade_6.Unit04.powers_of_whole_numbers_generator import PowersOfWholeNumbersGenerator
from generators.K_8.Grade_6.Unit05.comparing_absolute_values_generator import ComparingAbsoluteValuesGenerator
from generators.K_8.Grade_6.Unit05.comparing_negative_numbers_generator import ComparingNegativeNumbersGenerator
from generators.K_8.Grade_6.Unit05.intro_to_absolute_value_generator import IntroToAbsoluteValueGenerator
from generators.K_8.Grade_6.Unit05.intro_to_negative_numbers_generator import IntroToNegativeNumbersGenerator
from generators.K_8.Grade_6.Unit05.negative_symbol_as_opposite_generator import NegativeSymbolAsOppositeGenerator
from generators.K_8.Grade_6.Unit05.ordering_rational_numbers_generator import OrderingRationalNumbersGenerator
from generators.K_8.Grade_6.Unit05.rational_numbers_on_number_line_generator import RationalNumbersOnNumberLineGenerator
from generators.K_8.Grade_6.Unit06.combining_like_terms_generator import CombiningLikeTermsGenerator
from generators.K_8.Grade_6.Unit06.distributive_property_with_variables_generator import DistributivePropertyWithVariablesGenerator
from generators.K_8.Grade_6.Unit06.equivalent_expressions_generator import EquivalentExpressionsGenerator
from generators.K_8.Grade_6.Unit06.evaluating_expressions_with_multiple_variables_generator import EvaluatingExpressionsWithMultipleVariablesGenerator
from generators.K_8.Grade_6.Unit06.evaluating_expressions_word_problems_generator import EvaluatingExpressionsWordProblemsGenerator
from generators.K_8.Grade_6.Unit06.expression_value_intuition_generator import ExpressionValueIntuitionGenerator
from generators.K_8.Grade_6.Unit06.greatest_common_factor_generator import GreatestCommonFactorGenerator
from generators.K_8.Grade_6.Unit06.least_common_multiple_generator import LeastCommonMultipleGenerator
from generators.K_8.Grade_6.Unit06.parts_of_algebraic_expressions_generator import PartsOfAlgebraicExpressionsGenerator
from generators.K_8.Grade_6.Unit06.properties_of_numbers_generator import PropertiesOfNumbersGenerator
from generators.K_8.Grade_6.Unit06.substitution_and_evaluating_expressions_generator import SubstitutionAndEvaluatingExpressionsGenerator
from generators.K_8.Grade_6.Unit06.whole_numbers_and_integers_generator import WholeNumbersAndIntegersGenerator
from generators.K_8.Grade_6.Unit06.writing_algebraic_expressions_introduction_generator import WritingAlgebraicExpressionsIntroductionGenerator
from generators.K_8.Grade_6.Unit06.writing_basic_algebraic_expressions_word_problems_generator import WritingBasicAlgebraicExpressionsWordProblemsGenerator
from generators.K_8.Grade_6.Unit07.algebraic_equations_basics_generator import AlgebraicEquationsBasicsGenerator
from generators.K_8.Grade_6.Unit07.analyzing_relationships_between_variables_generator import AnalyzingRelationshipsBetweenVariablesGenerator
from generators.K_8.Grade_6.Unit07.dependent_and_independent_variables_generator import DependentAndIndependentVariablesGenerator
from generators.K_8.Grade_6.Unit07.finding_mistakes_in_one_step_equations_generator import FindingMistakesInOneStepEquationsGenerator
from generators.K_8.Grade_6.Unit07.intro_to_inequalities_with_variables_generator import IntroToInequalitiesWithVariablesGenerator
from generators.K_8.Grade_6.Unit07.one_step_addition_and_subtraction_equations_generator import OneStepAdditionAndSubtractionEquationsGenerator
from generators.K_8.Grade_6.Unit07.one_step_equation_word_problems_generator import OneStepEquationWordProblemsGenerator
from generators.K_8.Grade_6.Unit07.one_step_equations_intuition_generator import OneStepEquationsIntuitionGenerator
from generators.K_8.Grade_6.Unit07.one_step_multiplication_and_division_equations_generator import OneStepMultiplicationAndDivisionEquationsGenerator
from generators.K_8.Grade_6.Unit08.area_of_composite_figures_generator import AreaOfCompositeFiguresGenerator
from generators.K_8.Grade_6.Unit08.areas_of_parallelograms_generator import AreasOfParallelogramsGenerator
from generators.K_8.Grade_6.Unit08.areas_of_triangles_generator import AreasOfTrianglesGenerator
from generators.K_8.Grade_6.Unit09.distance_on_coordinate_plane_generator import DistanceOnCoordinatePlaneGenerator
from generators.K_8.Grade_6.Unit09.four_quadrants_generator import FourQuadrantsGenerator
from generators.K_8.Grade_6.Unit09.polygons_on_coordinate_plane_generator import PolygonsOnCoordinatePlaneGenerator
from generators.K_8.Grade_6.Unit10.geometric_solids_3d_shapes_generator import GeometricSolids3dShapesGenerator
from generators.K_8.Grade_6.Unit10.nets_of_3d_figures_generator import NetsOf3dFiguresGenerator
from generators.K_8.Grade_6.Unit10.surface_area_generator import SurfaceAreaGenerator
from generators.K_8.Grade_6.Unit10.volume_with_fractions_generator import VolumeWithFractionsGenerator
from generators.K_8.Grade_6.Unit10.volume_with_mini_cubes_generator import VolumeWithMiniCubesGenerator
from generators.K_8.Grade_6.Unit11.box_plots_generator import BoxPlotsGenerator
from generators.K_8.Grade_6.Unit11.comparing_data_displays_generator import ComparingDataDisplaysGenerator
from generators.K_8.Grade_6.Unit11.dot_plots_and_frequency_tables_generator import DotPlotsAndFrequencyTablesGenerator
from generators.K_8.Grade_6.Unit11.histograms_generator import HistogramsGenerator
from generators.K_8.Grade_6.Unit11.interquartile_range_iqr_generator import InterquartileRangeIqrGenerator
from generators.K_8.Grade_6.Unit11.mean_absolute_deviation_mad_generator import MeanAbsoluteDeviationMadGenerator
from generators.K_8.Grade_6.Unit11.mean_and_median_challenge_problems_generator import MeanAndMedianChallengeProblemsGenerator
from generators.K_8.Grade_6.Unit11.mean_and_median_generator import MeanAndMedianGenerator
from generators.K_8.Grade_6.Unit11.shape_of_data_distributions_generator import ShapeOfDataDistributionsGenerator
from generators.K_8.Grade_6.Unit11.statistical_questions_generator import StatisticalQuestionsGenerator
from generators.K_8.Grade_6.Unit12.fractions_review_generator import FractionsReviewGenerator
from generators.K_8.Grade_6.Unit12.introduction_to_khan_for_families_generator import IntroductionToKhanForFamiliesGenerator
from generators.K_8.Grade_6.Unit12.negative_numbers_review_generator import NegativeNumbersReviewGenerator
from generators.K_8.Grade_6.Unit12.ratios_review_generator import RatiosReviewGenerator
from generators.K_8.Grade_7.Unit01.compare_and_interpret_constants_generator import CompareAndInterpretConstantsGenerator
from generators.K_8.Grade_7.Unit01.constant_of_proportionality_generator import ConstantOfProportionalityGenerator
from generators.K_8.Grade_7.Unit01.equations_of_proportional_relationships_generator import EquationsOfProportionalRelationshipsGenerator
from generators.K_8.Grade_7.Unit01.graphs_of_proportional_relationships_generator import GraphsOfProportionalRelationshipsGenerator
from generators.K_8.Grade_7.Unit01.identifying_proportional_relationships_generator import IdentifyingProportionalRelationshipsGenerator
from generators.K_8.Grade_7.Unit01.writing_and_solving_proportions_generator import WritingAndSolvingProportionsGenerator
from generators.K_8.Grade_7.Unit02.converting_fractions_to_decimals_generator import ConvertingFractionsToDecimalsGenerator
from generators.K_8.Grade_7.Unit02.percent_word_problems_generator import PercentWordProblemsGenerator
from generators.K_8.Grade_7.Unit02.rate_problems_with_fractions_generator import RateProblemsWithFractionsGenerator
from generators.K_8.Grade_7.Unit03.adding_and_subtracting_integers_generator import AddingAndSubtractingIntegersGenerator
from generators.K_8.Grade_7.Unit03.adding_and_subtracting_negatives_variables_generator import AddingAndSubtractingNegativesVariablesGenerator
from generators.K_8.Grade_7.Unit03.adding_negative_numbers_fluently_generator import AddingNegativeNumbersFluentlyGenerator
from generators.K_8.Grade_7.Unit03.intro_to_adding_negative_numbers_generator import IntroToAddingNegativeNumbersGenerator
from generators.K_8.Grade_7.Unit03.intro_to_subtracting_negative_numbers_generator import IntroToSubtractingNegativeNumbersGenerator
from generators.K_8.Grade_7.Unit03.subtracting_negative_numbers_fluently_generator import SubtractingNegativeNumbersFluentlyGenerator
from generators.K_8.Grade_7.Unit04.absolute_value_rational_numbers_generator import AbsoluteValueRationalNumbersGenerator
from generators.K_8.Grade_7.Unit04.adding_and_subtracting_negative_fractions_generator import AddingAndSubtractingNegativeFractionsGenerator
from generators.K_8.Grade_7.Unit04.adding_and_subtracting_rational_numbers_generator import AddingAndSubtractingRationalNumbersGenerator
from generators.K_8.Grade_7.Unit04.addition_subtraction_word_problems_negatives_generator import AdditionSubtractionWordProblemsNegativesGenerator
from generators.K_8.Grade_7.Unit04.properties_of_addition_subtraction_generator import PropertiesOfAdditionSubtractionGenerator
from generators.K_8.Grade_7.Unit05.multiplication_division_word_problems_negatives_generator import MultiplicationDivisionWordProblemsNegativesGenerator
from generators.K_8.Grade_7.Unit05.multiply_and_divide_negative_fractions_generator import MultiplyAndDivideNegativeFractionsGenerator
from generators.K_8.Grade_7.Unit05.multiply_and_divide_negative_numbers_generator import MultiplyAndDivideNegativeNumbersGenerator
from generators.K_8.Grade_7.Unit05.multiply_with_negatives_generator import MultiplyWithNegativesGenerator
from generators.K_8.Grade_7.Unit05.order_of_operations_generator import OrderOfOperationsGenerator
from generators.K_8.Grade_7.Unit05.powers_with_rational_bases_generator import PowersWithRationalBasesGenerator
from generators.K_8.Grade_7.Unit05.properties_of_multiplication_division_generator import PropertiesOfMultiplicationDivisionGenerator
from generators.K_8.Grade_7.Unit05.rational_number_word_problems_generator import RationalNumberWordProblemsGenerator
from generators.K_8.Grade_7.Unit05.understanding_multiplying_dividing_fractions_generator import UnderstandingMultiplyingDividingFractionsGenerator
from generators.K_8.Grade_7.Unit06.combining_like_terms_generator import CombiningLikeTermsGenerator
from generators.K_8.Grade_7.Unit06.distributive_property_equivalent_expressions_generator import DistributivePropertyEquivalentExpressionsGenerator
from generators.K_8.Grade_7.Unit06.interpreting_linear_expressions_generator import InterpretingLinearExpressionsGenerator
from generators.K_8.Grade_7.Unit06.one_step_inequalities_generator import OneStepInequalitiesGenerator
from generators.K_8.Grade_7.Unit06.two_step_equation_word_problems_generator import TwoStepEquationWordProblemsGenerator
from generators.K_8.Grade_7.Unit06.two_step_equations_decimals_fractions_generator import TwoStepEquationsDecimalsFractionsGenerator
from generators.K_8.Grade_7.Unit06.two_step_equations_intro_generator import TwoStepEquationsIntroGenerator
from generators.K_8.Grade_7.Unit06.two_step_inequalities_generator import TwoStepInequalitiesGenerator
from generators.K_8.Grade_7.Unit07.basic_probability_generator import BasicProbabilityGenerator
from generators.K_8.Grade_7.Unit07.comparing_sampling_populations_generator import ComparingSamplingPopulationsGenerator
from generators.K_8.Grade_7.Unit07.compound_events_sample_spaces_generator import CompoundEventsSampleSpacesGenerator
from generators.K_8.Grade_7.Unit07.probability_models_generator import ProbabilityModelsGenerator
from generators.K_8.Grade_7.Unit08.scale_copies_generator import ScaleCopiesGenerator
from generators.K_8.Grade_7.Unit08.scale_drawings_generator import ScaleDrawingsGenerator
from generators.K_8.Grade_7.Unit09.area_circumference_challenge_generator import AreaCircumferenceChallengeGenerator
from generators.K_8.Grade_7.Unit09.area_circumference_circles_generator import AreaCircumferenceCirclesGenerator
from generators.K_8.Grade_7.Unit09.constructing_triangles_generator import ConstructingTrianglesGenerator
from generators.K_8.Grade_7.Unit09.missing_angle_problems_generator import MissingAngleProblemsGenerator
from generators.K_8.Grade_7.Unit09.slicing_geometric_shapes_generator import SlicingGeometricShapesGenerator
from generators.K_8.Grade_7.Unit09.vertical_complementary_supplementary_angles_generator import VerticalComplementarySupplementaryAnglesGenerator
from generators.K_8.Grade_7.Unit09.volume_surface_area_word_problems_generator import VolumeSurfaceAreaWordProblemsGenerator
from generators.K_8.Grade_8.Unit01.approximating_irrational_numbers_generator import ApproximatingIrrationalNumbersGenerator
from generators.K_8.Grade_8.Unit01.arithmetic_with_scientific_notation_generator import ArithmeticWithScientificNotationGenerator
from generators.K_8.Grade_8.Unit01.exponent_properties_integer_exponents_generator import ExponentPropertiesIntegerExponentsGenerator
from generators.K_8.Grade_8.Unit01.exponent_properties_intro_generator import ExponentPropertiesIntroGenerator
from generators.K_8.Grade_8.Unit01.exponents_with_negative_bases_generator import ExponentsWithNegativeBasesGenerator
from generators.K_8.Grade_8.Unit01.irrational_numbers_generator import IrrationalNumbersGenerator
from generators.K_8.Grade_8.Unit01.negative_exponents_generator import NegativeExponentsGenerator
from generators.K_8.Grade_8.Unit01.repeating_decimals_generator import RepeatingDecimalsGenerator
from generators.K_8.Grade_8.Unit01.scientific_notation_intro_generator import ScientificNotationIntroGenerator
from generators.K_8.Grade_8.Unit01.square_and_cube_roots_generator import SquareAndCubeRootsGenerator
from generators.K_8.Grade_8.Unit01.working_with_powers_of_10_generator import WorkingWithPowersOf10Generator
from generators.K_8.Grade_8.Unit02.equations_with_parentheses_generator import EquationsWithParenthesesGenerator
from generators.K_8.Grade_8.Unit02.equations_with_variables_on_both_sides_generator import EquationsWithVariablesOnBothSidesGenerator
from generators.K_8.Grade_8.Unit02.number_of_solutions_to_equations_generator import NumberOfSolutionsToEquationsGenerator
from generators.K_8.Grade_8.Unit02.scientific_notation_word_problems_generator import ScientificNotationWordProblemsGenerator
from generators.K_8.Grade_8.Unit03.comparing_linear_functions_generator import ComparingLinearFunctionsGenerator
from generators.K_8.Grade_8.Unit03.constructing_linear_models_generator import ConstructingLinearModelsGenerator
from generators.K_8.Grade_8.Unit03.equations_word_problems_generator import EquationsWordProblemsGenerator
from generators.K_8.Grade_8.Unit03.functions_generator import FunctionsGenerator
from generators.K_8.Grade_8.Unit03.graphing_proportional_relationships_generator import GraphingProportionalRelationshipsGenerator
from generators.K_8.Grade_8.Unit03.graphing_slope_intercept_form_generator import GraphingSlopeInterceptFormGenerator
from generators.K_8.Grade_8.Unit03.intercepts_generator import InterceptsGenerator
from generators.K_8.Grade_8.Unit03.intro_to_slope_intercept_form_generator import IntroToSlopeInterceptFormGenerator
from generators.K_8.Grade_8.Unit03.linear_models_generator import LinearModelsGenerator
from generators.K_8.Grade_8.Unit03.recognizing_functions_generator import RecognizingFunctionsGenerator
from generators.K_8.Grade_8.Unit03.slope_generator import SlopeGenerator
from generators.K_8.Grade_8.Unit03.solutions_to_linear_equations_generator import SolutionsToLinearEquationsGenerator
from generators.K_8.Grade_8.Unit03.writing_slope_intercept_equations_generator import WritingSlopeInterceptEquationsGenerator
from generators.K_8.Grade_8.Unit04.intro_to_systems_of_equations_generator import IntroToSystemsOfEquationsGenerator
from generators.K_8.Grade_8.Unit04.linear_and_nonlinear_functions_generator import LinearAndNonlinearFunctionsGenerator
from generators.K_8.Grade_8.Unit04.number_of_solutions_to_systems_generator import NumberOfSolutionsToSystemsGenerator
from generators.K_8.Grade_8.Unit04.solving_systems_with_substitution_generator import SolvingSystemsWithSubstitutionGenerator
from generators.K_8.Grade_8.Unit04.systems_of_equations_with_graphing_generator import SystemsOfEquationsWithGraphingGenerator
from generators.K_8.Grade_8.Unit05.angles_between_intersecting_lines_generator import AnglesBetweenIntersectingLinesGenerator
from generators.K_8.Grade_8.Unit05.pythagorean_theorem_and_distance_generator import PythagoreanTheoremAndDistanceGenerator
from generators.K_8.Grade_8.Unit05.pythagorean_theorem_application_generator import PythagoreanTheoremApplicationGenerator
from generators.K_8.Grade_8.Unit05.pythagorean_theorem_generator import PythagoreanTheoremGenerator
from generators.K_8.Grade_8.Unit05.pythagorean_theorem_proofs_generator import PythagoreanTheoremProofsGenerator
from generators.K_8.Grade_8.Unit05.systems_of_equations_word_problems_generator import SystemsOfEquationsWordProblemsGenerator
from generators.K_8.Grade_8.Unit05.triangle_angles_generator import TriangleAnglesGenerator
from generators.K_8.Grade_8.Unit06.dilations_generator import DilationsGenerator
from generators.K_8.Grade_8.Unit06.properties_and_definitions_of_transformations_generator import PropertiesAndDefinitionsOfTransformationsGenerator
from generators.K_8.Grade_8.Unit06.reflections_generator import ReflectionsGenerator
from generators.K_8.Grade_8.Unit06.rotations_generator import RotationsGenerator
from generators.K_8.Grade_8.Unit06.transformations_intro_generator import TransformationsIntroGenerator
from generators.K_8.Grade_8.Unit06.translations_generator import TranslationsGenerator
from generators.K_8.Grade_8.Unit06.volume_generator import VolumeGenerator
from generators.K_8.Grade_8.Unit07.congruence_and_similarity_generator import CongruenceAndSimilarityGenerator
from generators.K_8.Grade_8.Unit07.estimating_lines_of_best_fit_generator import EstimatingLinesOfBestFitGenerator
from generators.K_8.Grade_8.Unit07.interpreting_scatter_plots_generator import InterpretingScatterPlotsGenerator
from generators.K_8.Grade_8.Unit07.introduction_to_scatter_plots_generator import IntroductionToScatterPlotsGenerator
from generators.K_8.Grade_8.Unit08.two_way_tables_generator import TwoWayTablesGenerator
from generators.K_8.Kindergarten.Unit01.counting_beyond_20_generator import CountingBeyond20Generator
from generators.K_8.Kindergarten.Unit01.counting_up_to_10_generator import CountingUpTo10Generator
from generators.K_8.Kindergarten.Unit01.counting_up_to_20_generator import CountingUpTo20Generator
from generators.K_8.Kindergarten.Unit01.counting_up_to_3_generator import CountingUpTo3Generator
from generators.K_8.Kindergarten.Unit01.counting_up_to_5_generator import CountingUpTo5Generator
from generators.K_8.Kindergarten.Unit02.comparing_sizes_generator import ComparingSizesGenerator
from generators.K_8.Kindergarten.Unit02.equal_quantities_generator import EqualQuantitiesGenerator
from generators.K_8.Kindergarten.Unit02.more_and_less_generator import MoreAndLessGenerator
from generators.K_8.Kindergarten.Unit03.creating_patterns_generator import CreatingPatternsGenerator
from generators.K_8.Kindergarten.Unit03.extending_patterns_generator import ExtendingPatternsGenerator
from generators.K_8.Kindergarten.Unit03.recognizing_patterns_generator import RecognizingPatternsGenerator
from generators.K_8.Kindergarten.Unit04.addition_up_to_10_generator import AdditionUpTo10Generator
from generators.K_8.Kindergarten.Unit04.addition_up_to_5_generator import AdditionUpTo5Generator
from generators.K_8.Kindergarten.Unit05.subtraction_up_to_10_generator import SubtractionUpTo10Generator
from generators.K_8.Kindergarten.Unit05.subtraction_up_to_5_generator import SubtractionUpTo5Generator
from generators.K_8.Kindergarten.Unit06.above_below_beside_between_generator import AboveBelowBesideBetweenGenerator
from generators.K_8.Kindergarten.Unit06.left_right_inside_outside_generator import LeftRightInsideOutsideGenerator
from generators.K_8.Kindergarten.Unit07.days_and_weeks_generator import DaysAndWeeksGenerator
from generators.K_8.Kindergarten.Unit07.reading_clocks_introduction_generator import ReadingClocksIntroductionGenerator
from generators.K_8.Kindergarten.Unit07.seasons_generator import SeasonsGenerator
from generators.K_8.Kindergarten.Unit08.basic_probability_generator import BasicProbabilityGenerator
from generators.K_8.Kindergarten.Unit08.classifying_objects_generator import ClassifyingObjectsGenerator
from generators.K_8.Kindergarten.Unit08.ordering_objects_generator import OrderingObjectsGenerator
from generators.K_8.Kindergarten.Unit08.reading_simple_graphs_generator import ReadingSimpleGraphsGenerator
from generators.K_8.Kindergarten.Unit08.sorting_objects_generator import SortingObjectsGenerator
from generators.K_8.Kindergarten.Unit09.coin_recognition_generator import CoinRecognitionGenerator
from generators.K_8.Kindergarten.Unit09.coin_values_generator import CoinValuesGenerator
from generators.K_8.Kindergarten.Unit09.comparing_lengths_generator import ComparingLengthsGenerator
from generators.K_8.Kindergarten.Unit09.comparing_sizes_measurement_generator import ComparingSizesMeasurementGenerator
from generators.K_8.Kindergarten.Unit10.circles_and_squares_generator import CirclesAndSquaresGenerator
from generators.K_8.Kindergarten.Unit10.cones_and_cylinders_generator import ConesAndCylindersGenerator
from generators.K_8.Kindergarten.Unit10.cubes_and_spheres_generator import CubesAndSpheresGenerator
from generators.K_8.Kindergarten.Unit10.triangles_and_rectangles_generator import TrianglesAndRectanglesGenerator


# Generator registry mapping
# Structure: {subject_path: {topic_name: GeneratorClass}}
GENERATOR_REGISTRY = {
    "High-School - AP Statistics": {
    },
    "High-School - Algebra": {
        "Absolute Value": AbsoluteValueGenerator,
        "Absolute Value Inequalities": AbsoluteValueInequalitiesGenerator,
        "Add And Subtract Polynomials": AddAndSubtractPolynomialsGenerator,
        "Advanced Properties Of Radicals Multiplication Fractions": AdvancedPropertiesOfRadicalsMultiplicationFractionsGenerator,
        "Combining Like Terms": CombiningLikeTermsGenerator,
        "Completing The Square": CompletingTheSquareGenerator,
        "Compound Inequalities": CompoundInequalityGenerator,
        "Compound Inequality Word Problems": CompoundInequalityWordProblemsGenerator,
        "Constructing Geometric Sequences": ConstructingGeometricSequencesGenerator,
        "Dependent And Independent Variables": DependentAndIndependentVariablesGenerator,
        "Domain And Range": DomainAndRangeGenerator,
        "Domain Range": DomainRangeGenerator,
        "Equations Intro": EquationsIntroGenerator,
        "Equivalent Exponential Review": EquivalentExponentialReviewGenerator,
        "Evaluating Expressions": EvaluatingExpressionsGenerator,
        "Evaluating Expressions With Exponents Greater Than 1": EvaluatingExpressionsWithExponentsGreaterThan1Generator,
        "Evaluating Expressions With Multiple Terms": EvaluatingExpressionsWithMultipleTermsGenerator,
        "Evaluating Expressions With Multiple Variables": EvaluatingExpressionsWithMultipleVariablesGenerator,
        "Expanding And Simplifying Expressions With Exponents": ExpandingAndSimplifyingExpressionsWithExponentsGenerator,
        "Expanding And Simplifying Variables With Exponents": ExpandingAndSimplifyingVariablesWithExponentsGenerator,
        "Expanding Exponents": ExpandingExponentsGenerator,
        "Exponent Properties": ExponentPropertiesGenerator,
        "Exponential Decay": ExponentialDecayGenerator,
        "Exponential Functions": ExponentialFunctionsGenerator,
        "Exponential Functions Using Tables": ExponentialFunctionsUsingTablesGenerator,
        "Exponential Growth": ExponentialGrowthGenerator,
        "Exponential Growth Decay": ExponentialGrowthDecayGenerator,
        "Exponents": ExponentsGenerator,
        "Exponents Properties": ExponentsPropertiesGenerator,
        "Factor By Grouping": FactorByGroupingGenerator,
        "Factoring": FactoringGenerator,
        "Factoring Monomials": FactoringMonomialsGenerator,
        "Factoring Polynomials With Common Factors": FactoringPolynomialsWithCommonFactorsGenerator,
        "Functions": FunctionsGenerator,
        "Functions What Is The Point Vs An Equation Function Notation": FunctionsWhatIsThePointVsAnEquationFunctionNotationGenerator,
        "Inequalities": InequalitiesGenerator,
        "Inequality Word Problems": InequalityWordProblemsGenerator,
        "Inputs Outputs": InputsOutputsGenerator,
        "Inputs Outputs Functions Review": InputsOutputsFunctionsReviewGenerator,
        "Inputs Outputs Review": InputsOutputsReviewGenerator,
        "Intercepts": InterceptsGenerator,
        "Interpreting Domain And Range": InterpretingDomainAndRangeGenerator,
        "Interpreting Quadratic Functions Word Problems": InterpretingQuadraticFunctionsWordProblemsGenerator,
        "Linear Equation Word Problems": LinearEquationWordProblemsGenerator,
        "Linear Equations": LinearEquationsGenerator,
        "Linear Vs Exponential Growth": LinearVsExponentialGrowthGenerator,
        "Literal Equations": LiteralEquationsGenerator,
        "Modeling Exponential Functions": ModelingExponentialFunctionsGenerator,
        "Modeling With Sequences": ModelingWithSequencesGenerator,
        "Multi Step Inequalities": MultiStepInequalitiesGenerator,
        "Multi Step Inequality Word Problems": MultiStepInequalityWordProblemsGenerator,
        "Multiple Terms In A Single Expression": MultipleTermsInASingleExpressionGenerator,
        "Multiplying Monomials 1X1": MultiplyingMonomials1x1Generator,
        "Multiplying Monomials And Binomials 1X2": MultiplyingMonomialsAndBinomials1x2Generator,
        "Multiplying Polynomials 2X2 2X3 Etc": MultiplyingPolynomials2x22x3EtcGenerator,
        "Number Properties": NumberPropertiesGenerator,
        "Order Of Operations": OrderOfOperationsGenerator,
        "Parts Of A Term Recognizing That Coefficients Are Multiplication": PartsOfATermRecognizingThatCoefficientsAreMultiplicationGenerator,
        "Parts Of Term": PartsOfTermGenerator,
        "Parts Of Term Exponents Review": PartsOfTermExponentsReviewGenerator,
        "Polynomial Operations": PolynomialOperationsGenerator,
        "Properties Of Exponents": PropertiesOfExponentsGenerator,
        "Property Equality Add Sub": PropertyEqualityAddSubGenerator,
        "Property Equality Mult Div": PropertyEqualityMultDivGenerator,
        "Quadratic Equations": QuadraticEquationsGenerator,
        "Quadratic Equations Parabola": QuadraticEquationsParabolaGenerator,
        "Quadratic Formula Hard To Use The Three Main Methods And Completing The Square": QuadraticFormulaHardToUseTheThreeMainMethodsAndCompletingTheSquareGenerator,
        "Quadratic Functions": QuadraticFunctionsGenerator,
        "Quadratic Graphing": QuadraticGraphingGenerator,
        "Quadratic Inequalities": QuadraticInequalitiesGenerator,
        "Quadratics By Factoring": QuadraticsByFactoringGenerator,
        "Radical Properties": RadicalPropertiesGenerator,
        "Simple Inequalities": SimpleInequalitiesGenerator,
        "Slope": SlopeGenerator,
        "Solutions": SolutionsGenerator,
        "Solving Quadratic Equations Using Square Roots No Other Terms Except X Squared": SolvingQuadraticEquationsUsingSquareRootsNoOtherTermsExceptXSquaredGenerator,
        "Solving Quadratics By Factoring Factor For The Roots Use Xp Over 2 To Find Vertex": SolvingQuadraticsByFactoringFactorForTheRootsUseXPlusPOver2ToFindVertexGenerator,
        "Square Roots": SquareRootsGenerator,
        "Standard Form Of Quadratics": StandardFormOfQuadraticsGenerator,
        "Substitution": SubstitutionGenerator,
        "Systems Of Equations Using Elimination": SystemsOfEquationsUsingEliminationGenerator,
        "Systems Of Equations Using Substitution": SystemsOfEquationsUsingSubstitutionGenerator,
        "Systems Of Inequalities": SystemsOfInequalitiesGenerator,
        "Systems Of Quadratic Equations": SystemsOfQuadraticEquationsGenerator,
        "Systems Of Quadratic Inequalities": SystemsOfQuadraticInequalitiesGenerator,
        "The Coordinate Plane": TheCoordinatePlaneGenerator,
        "To Factor Using Perfect Squares": ToFactorUsingPerfectSquaresGenerator,
        "Two Step Equations": TwoStepEquationsGenerator,
        "Two Step Inequalities": TwoStepInequalitiesGenerator,
        "Two Variable Linear Equations": TwoVariableLinearEquationsGenerator,
        "Using Standard Form B Over 2A Plus Solve For When X Equals 0": UsingStandardFormBOver2aPlusSolveForWhenXEquals0Generator,
        "Variables": VariablesGenerator,
        "Variables Both Sides": VariablesBothSidesGenerator,
        "Vertex Form": VertexFormGenerator,
        "Writing Exponential Functions": WritingExponentialFunctionsGenerator,
        "Writing Expression Word Problems": WritingExpressionWordProblemsGenerator,
        "Writing Point Slope Form Equations": WritingPointSlopeFormEquationsGenerator,
        "Writing Quadratic Functions": WritingQuadraticFunctionsGenerator,
        "Writing Slope Intercept Equations": WritingSlopeInterceptEquationsGenerator,
        "Writing Standard Form Equations": WritingStandardFormEquationsGenerator,
        "Writing Systems Of Equation Word Problems": WritingSystemsOfEquationWordProblemsGenerator,
        "Writing Systems Of Inequalities": WritingSystemsOfInequalitiesGenerator,
        "X And Y Intercepts": XAndYInterceptsGenerator,
    },
    "High-School - Algebra 2": {
    },
    "High-School - Calculus": {
    },
    "High-School - Geometry": {
    },
    "High-School - Grade 8": {
    },
    "High-School - IM1": {
    },
    "High-School - IM2": {
    },
    "High-School - IM3": {
    },
    "K-8 - Grade 1": {
        "Addition And Subtraction Up To 20": AdditionAndSubtractionUpTo20Generator,
        "Addition And Subtraction With Two Digits": AdditionAndSubtractionWithTwoDigitsGenerator,
        "Addition Strategies Up To 10": AdditionStrategiesUpTo10Generator,
        "Addition Strategies Up To 20": AdditionStrategiesUpTo20Generator,
        "Addition Up To 10": AdditionUpTo10Generator,
        "Addition Up To 20": AdditionUpTo20Generator,
        "Addition With Two Digits": AdditionWithTwoDigitsGenerator,
        "Addition Word Problems Up To 10": AdditionWordProblemsUpTo10Generator,
        "Addition Word Problems Up To 20": AdditionWordProblemsUpTo20Generator,
        "Area Introduction": AreaIntroductionGenerator,
        "Coin Recognition": CoinRecognitionGenerator,
        "Comparing 2D Shapes": Comparing2dShapesGenerator,
        "Comparing Lengths": ComparingLengthsGenerator,
        "Comparing Numbers": ComparingNumbersGenerator,
        "Counting And Numbers": CountingAndNumbersGenerator,
        "Counting Coins": CountingCoinsGenerator,
        "Counting Unit Squares": CountingUnitSquaresGenerator,
        "Days Months And Seasons": DaysMonthsAndSeasonsGenerator,
        "Even And Odd Numbers": EvenAndOddNumbersGenerator,
        "Extending Patterns": ExtendingPatternsGenerator,
        "Identifying 2D Shapes": Identifying2dShapesGenerator,
        "Measuring With Non Standard Units": MeasuringWithNonStandardUnitsGenerator,
        "Ordering Numbers": OrderingNumbersGenerator,
        "Place Value Tens And Ones": PlaceValueTensAndOnesGenerator,
        "Reading Bar Graphs": ReadingBarGraphsGenerator,
        "Reading Picture Graphs": ReadingPictureGraphsGenerator,
        "Recognizing Patterns": RecognizingPatternsGenerator,
        "Skip Counting": SkipCountingGenerator,
        "Subtraction Strategies Up To 10": SubtractionStrategiesUpTo10Generator,
        "Subtraction Strategies Up To 20": SubtractionStrategiesUpTo20Generator,
        "Subtraction Up To 10": SubtractionUpTo10Generator,
        "Subtraction Up To 20": SubtractionUpTo20Generator,
        "Subtraction With Two Digits": SubtractionWithTwoDigitsGenerator,
        "Subtraction Word Problems Up To 10": SubtractionWordProblemsUpTo10Generator,
        "Subtraction Word Problems Up To 20": SubtractionWordProblemsUpTo20Generator,
        "Telling Time Hour Half Hour": TellingTimeHourHalfHourGenerator,
        "Understand Addition": UnderstandAdditionGenerator,
        "Understand Subtraction": UnderstandSubtractionGenerator,
    },
    "K-8 - Grade 2": {
        "Add And Subtract Within 20": AddAndSubtractWithin20Generator,
        "Add Subtract Within 100 Word Problems": AddSubtractWithin100WordProblemsGenerator,
        "Add Subtract Within 100 Word Problems Multi Step": AddSubtractWithin100WordProblemsMultiStepGenerator,
        "Add Using Arrays": AddUsingArraysGenerator,
        "Add Within 20": AddWithin20Generator,
        "Adding Up To Four 2 Digit Numbers": AddingUpToFour2DigitNumbersGenerator,
        "Addition And Subtraction Missing Values": AdditionAndSubtractionMissingValuesGenerator,
        "Bar Graphs": BarGraphsGenerator,
        "Comparing 2 And 3 Digit Numbers": Comparing2And3DigitNumbersGenerator,
        "Counting Money": CountingMoneyGenerator,
        "Counting Patterns Within 1000": CountingPatternsWithin1000Generator,
        "Equal Parts Of Shapes": EqualPartsOfShapesGenerator,
        "Estimate Lengths": EstimateLengthsGenerator,
        "Even And Odd Numbers": EvenAndOddNumbersGenerator,
        "Intro To Place Value": IntroToPlaceValueGenerator,
        "Length Word Problems": LengthWordProblemsGenerator,
        "Line Plots": LinePlotsGenerator,
        "Measure Lengths": MeasureLengthsGenerator,
        "Numbers In Standard Word Expanded Form": NumbersInStandardWordExpandedFormGenerator,
        "Partition Rectangles": PartitionRectanglesGenerator,
        "Picture Graphs": PictureGraphsGenerator,
        "Regroup Whole Numbers": RegroupWholeNumbersGenerator,
        "Shapes": ShapesGenerator,
        "Strategies For Adding Within 100": StrategiesForAddingWithin100Generator,
        "Strategies For Adding Within 1000": StrategiesForAddingWithin1000Generator,
        "Strategies For Subtracting Within 1000": StrategiesForSubtractingWithin1000Generator,
        "Subtract Within 20": SubtractWithin20Generator,
        "Time": TimeGenerator,
        "Units Of Length": UnitsOfLengthGenerator,
        "Visually Adding Within 100": VisuallyAddingWithin100Generator,
        "Visually Adding Within 1000": VisuallyAddingWithin1000Generator,
        "Visually Subtract Within 100": VisuallySubtractWithin100Generator,
    },
    "K-8 - Grade 3": {
        "Adding With Regrouping Within 1000": AddingWithRegroupingWithin1000Generator,
        "Addition And Subtraction Word Problems": AdditionAndSubtractionWordProblemsGenerator,
        "Area Introduction": AreaIntroductionGenerator,
        "Associative Property Of Multiplication": AssociativePropertyGenerator,
        "Bar Graphs": BarGraphsGenerator,
        "Comparing Fractions": ComparingFractionsGenerator,
        "Comparing Fractions Of Different Wholes": ComparingFractionsOfDifferentWholesGenerator,
        "Count Unit Squares To Find Area": CountUnitSquaresToFindAreaGenerator,
        "Distributive Property": DistributivePropertyGenerator,
        "Divide By 1 2 Or 4": DivideBy1_2_Or4Generator,
        "Divide By 3 Or 6": DivideBy3Or6Generator,
        "Divide By 5 Or 10": DivideBy5Or10Generator,
        "Divide By 7 8 Or 9": DivideBy7_8_Or9Generator,
        "Division Intro": DivisionIntroGenerator,
        "Elapsed Time": ElapsedTimeGenerator,
        "Equivalent Fractions": EquivalentFractionsGenerator,
        "Estimate To Add Multi Digit Numbers": EstimateToAddMultiDigitNumbersGenerator,
        "Estimate To Subtract Multi Digit Numbers": EstimateToSubtractMultiDigitNumbersGenerator,
        "Estimation Word Problems": EstimationWordProblemsGenerator,
        "Fractions And Whole Numbers": FractionsAndWholeNumbersGenerator,
        "Fractions In Contexts": FractionsInContextsGenerator,
        "Fractions Intro": FractionsIntroGenerator,
        "Letters And Symbols In Multiplication And Division Equations": LettersAndSymbolsGenerator,
        "Line Plots With Fractions": LinePlotsWithFractionsGenerator,
        "Mass": MassGenerator,
        "Multiplication And Division Word Problems": MultiplicationDivisionWordProblemsGenerator,
        "Multiplication As Equal Groups": MultiplicationAsEqualGroupsGenerator,
        "Multiplication As Groups Of Objects": MultiplicationAsGroupsOfObjectsGenerator,
        "Multiply By 0 Or 1": MultiplyBy0Or1Generator,
        "Multiply By 2 Or 4": MultiplyBy2Or4Generator,
        "Multiply By 3 Or 6": MultiplyBy3Or6Generator,
        "Multiply By 5 Or 10": MultiplyBy5Or10Generator,
        "Multiply By 7 8 Or 9": MultiplyBy7_8Or9Generator,
        "Multiply To Find Area": MultiplyToFindAreaGenerator,
        "Multiplying By Tens": MultiplyingByTensGenerator,
        "One And Two Step Word Problems": OneAndTwoStepWordProblemsGenerator,
        "Perimeter": PerimeterGenerator,
        "Perimeter Word Problems": PerimeterWordProblemsGenerator,
        "Picture Graphs": PictureGraphsGenerator,
        "Rounding To Nearest 10 Or 100": RoundingToNearest10Or100Generator,
        "Subtracting With Regrouping Within 1000": SubtractingWithRegroupingWithin1000Generator,
        "Telling Time": TellingTimeGenerator,
        "Two Step Expressions": TwoStepExpressionsGenerator,
        "Volume": VolumeGenerator,
    },
    "K-8 - Grade 4": {
        "Adding And Subtracting Fractions With Like Denominators": AddingAndSubtractingFractionsWithLikeDenominatorsGenerator,
        "Adding And Subtracting Fractions Word Problems": AddingAndSubtractingFractionsWordProblemsGenerator,
        "Adding And Subtracting Mixed Numbers": AddingAndSubtractingMixedNumbersGenerator,
        "Adding And Subtracting Mixed Numbers Word Problems": AddingAndSubtractingMixedNumbersWordProblemsGenerator,
        "Adding Multi Digit Numbers": AddingMultiDigitNumbersGenerator,
        "Angle Introduction": AngleIntroductionGenerator,
        "Area And Perimeter": AreaAndPerimeterGenerator,
        "Classifying Geometric Shapes": ClassifyingGeometricShapesGenerator,
        "Classifying Triangles": ClassifyingTrianglesGenerator,
        "Common Denominators": CommonDenominatorsGenerator,
        "Common Fractions And Decimals": CommonFractionsAndDecimalsGenerator,
        "Comparing Decimals": ComparingDecimalsGenerator,
        "Comparing Decimals Visually": ComparingDecimalsVisuallyGenerator,
        "Comparing Fractions With Unlike Denominators": ComparingFractionsWithUnlikeDenominatorsGenerator,
        "Comparing Fractions With Unlike Denominators Visually": ComparingFractionsWithUnlikeDenominatorsVisuallyGenerator,
        "Comparing Multi Digit Numbers": ComparingMultiDigitNumbersGenerator,
        "Comparing With Multiplication": ComparingWithMultiplicationGenerator,
        "Converting Units Of Length": ConvertingUnitsOfLengthGenerator,
        "Converting Units Of Mass": ConvertingUnitsOfMassGenerator,
        "Converting Units Of Time": ConvertingUnitsOfTimeGenerator,
        "Converting Units Of Volume": ConvertingUnitsOfVolumeGenerator,
        "Decimal Fractions": DecimalFractionsGenerator,
        "Decimal Fractions Greater Than 1": DecimalFractionsGreaterThan1Generator,
        "Decimals In Word Form": DecimalsInWordFormGenerator,
        "Decimals On The Number Line": DecimalsOnTheNumberLineGenerator,
        "Decomposing Angles": DecomposingAnglesGenerator,
        "Decomposing Fractions": DecomposingFractionsGenerator,
        "Divide Multiples Of 10 100 And 1000 By 1 Digit Numbers": DivideMultiplesOf10100And1000By1DigitNumbersGenerator,
        "Division With Area Models": DivisionWithAreaModelsGenerator,
        "Division With Place Value": DivisionWithPlaceValueGenerator,
        "Equivalent Fractions": EquivalentFractionsGenerator,
        "Estimate Products": EstimateProductsGenerator,
        "Estimate Products 2 Digit Numbers": EstimateProducts2DigitNumbersGenerator,
        "Estimate Quotients": EstimateQuotientsGenerator,
        "Estimating Length": EstimatingLengthGenerator,
        "Estimating Mass": EstimatingMassGenerator,
        "Estimating Volume": EstimatingVolumeGenerator,
        "Factors And Multiples": FactorsAndMultiplesGenerator,
        "Fractions With Denominators Of 10 And 100": FractionsWithDenominatorsOf10And100Generator,
        "How 10 Relates To Place Value": How10RelatesToPlaceValueGenerator,
        "Line Of Symmetry": LineOfSymmetryGenerator,
        "Line Plots With Fractions": LinePlotsWithFractionsGenerator,
        "Math Patterns": MathPatternsGenerator,
        "Measuring Angles": MeasuringAnglesGenerator,
        "Mixed Numbers": MixedNumbersGenerator,
        "Multi Digit Division With Partial Quotients": MultiDigitDivisionWithPartialQuotientsGenerator,
        "Multi Digit Multiplication Place Value And Area Models": MultiDigitMultiplicationPlaceValueAndAreaModelsGenerator,
        "Multi Step Word Problems": MultiStepWordProblemsGenerator,
        "Multiplication By 10S 100S And 1000S": MultiplicationBy10s100sAnd1000sGenerator,
        "Multiplication Division Word Problems": MultiplicationDivisionWordProblemsGenerator,
        "Multiply 2 Digit Numbers With Area Models": Multiply2DigitNumbersWithAreaModelsGenerator,
        "Multiply 2 Digit Numbers With Partial Products": Multiply2DigitNumbersWithPartialProductsGenerator,
        "Multiply By 10S": MultiplyBy10sGenerator,
        "Multiply With Partial Products": MultiplyWithPartialProductsGenerator,
        "Multiplying Fractions And Whole Numbers Visually": MultiplyingFractionsAndWholeNumbersVisuallyGenerator,
        "Multiplying Whole Numbers And Fractions": MultiplyingWholeNumbersAndFractionsGenerator,
        "Multiplying Whole Numbers And Fractions Word Problems": MultiplyingWholeNumbersAndFractionsWordProblemsGenerator,
        "Multiplying Whole Numbers And Mixed Numbers": MultiplyingWholeNumbersAndMixedNumbersGenerator,
        "Parallel And Perpendicular": ParallelAndPerpendicularGenerator,
        "Place Value": PlaceValueGenerator,
        "Prime And Composite Numbers": PrimeAndCompositeNumbersGenerator,
        "Regrouping Decimals": RegroupingDecimalsGenerator,
        "Regrouping Whole Numbers": RegroupingWholeNumbersGenerator,
        "Remainders": RemaindersGenerator,
        "Rounding Whole Numbers": RoundingWholeNumbersGenerator,
        "Subtracting Multi Digit Numbers": SubtractingMultiDigitNumbersGenerator,
        "Time": TimeGenerator,
        "Types Of Plane Figures": TypesOfPlaneFiguresGenerator,
        "Understanding Angle Measurement": UnderstandingAngleMeasurementGenerator,
        "Writing Decimals As Fractions": WritingDecimalsAsFractionsGenerator,
        "Writing Fractions As Decimals": WritingFractionsAsDecimalsGenerator,
        "Writing Whole Numbers In Expanded Form": WritingWholeNumbersInExpandedFormGenerator,
        "Writing Whole Numbers In Written Form": WritingWholeNumbersInWrittenFormGenerator,
    },
    "K-8 - Grade 5": {
        "Adding Decimals Hundredths": AddingDecimalsHundredthsGenerator,
        "Adding Decimals Intro": AddingDecimalsIntroGenerator,
        "Adding Decimals Tenths": AddingDecimalsTenthsGenerator,
        "Adding Subtracting Fractions Unlike": AddingSubtractingFractionsUnlikeGenerator,
        "Adding Subtracting Mixed Numbers": AddingSubtractingMixedNumbersGenerator,
        "Common Denominators": CommonDenominatorsGenerator,
        "Common Fractions Decimals": CommonFractionsDecimalsGenerator,
        "Comparing Decimals": ComparingDecimalsGenerator,
        "Decimal Place Value Intro": DecimalPlaceValueIntroGenerator,
        "Decimals Different Forms": DecimalsDifferentFormsGenerator,
        "Decimals Expanded Form": DecimalsExpandedFormGenerator,
        "Decimals On Number Line": DecimalsOnNumberLineGenerator,
        "Decimals Written Form": DecimalsWrittenFormGenerator,
        "Fractions Unlike Denominators Strategies": FractionsUnlikeDenominatorsStrategiesGenerator,
        "Fractions Word Problems": FractionsWordProblemsGenerator,
        "Multi Digit Division": MultiDigitDivisionGenerator,
        "Multi Digit Division Estimation": MultiDigitDivisionEstimationGenerator,
        "Multi Digit Multiplication": MultiDigitMultiplicationGenerator,
        "Multi Digit Multiplication Estimation": MultiDigitMultiplicationEstimationGenerator,
        "Rounding Decimals": RoundingDecimalsGenerator,
        "Subtracting Decimals Hundredths": SubtractingDecimalsHundredthsGenerator,
        "Subtracting Decimals Intro": SubtractingDecimalsIntroGenerator,
        "Subtracting Decimals Tenths": SubtractingDecimalsTenthsGenerator,
    },
    "K-8 - Grade 6": {
        "Adding And Subtracting Decimals Word Problems": AddingAndSubtractingDecimalsWordProblemsGenerator,
        "Adding Decimals": AddingDecimalsGenerator,
        "Algebraic Equations Basics": AlgebraicEquationsBasicsGenerator,
        "Analyzing Relationships Between Variables": AnalyzingRelationshipsBetweenVariablesGenerator,
        "Area Of Composite Figures": AreaOfCompositeFiguresGenerator,
        "Areas Of Parallelograms": AreasOfParallelogramsGenerator,
        "Areas Of Triangles": AreasOfTrianglesGenerator,
        "Box Plots": BoxPlotsGenerator,
        "Combining Like Terms": CombiningLikeTermsGenerator,
        "Comparing Absolute Values": ComparingAbsoluteValuesGenerator,
        "Comparing Data Displays": ComparingDataDisplaysGenerator,
        "Comparing Negative Numbers": ComparingNegativeNumbersGenerator,
        "Dependent And Independent Variables": DependentAndIndependentVariablesGenerator,
        "Distance On Coordinate Plane": DistanceOnCoordinatePlaneGenerator,
        "Distributive Property With Variables": DistributivePropertyWithVariablesGenerator,
        "Dividing Decimals": DividingDecimalsGenerator,
        "Dividing Fractions And Whole Numbers": DividingFractionsAndWholeNumbersGenerator,
        "Dividing Fractions By Fractions": DividingFractionsByFractionsGenerator,
        "Dividing Whole Numbers": DividingWholeNumbersGenerator,
        "Dot Plots And Frequency Tables": DotPlotsAndFrequencyTablesGenerator,
        "Equivalent Expressions": EquivalentExpressionsGenerator,
        "Equivalent Ratios": EquivalentRatiosGenerator,
        "Equivalent Representations Of Percent Problems": EquivalentRepresentationsOfPercentProblemsGenerator,
        "Evaluating Expressions With Multiple Variables": EvaluatingExpressionsWithMultipleVariablesGenerator,
        "Evaluating Expressions Word Problems": EvaluatingExpressionsWordProblemsGenerator,
        "Expression Value Intuition": ExpressionValueIntuitionGenerator,
        "Finding Mistakes In One Step Equations": FindingMistakesInOneStepEquationsGenerator,
        "Four Quadrants": FourQuadrantsGenerator,
        "Fractions Review": FractionsReviewGenerator,
        "Geometric Solids 3D Shapes": GeometricSolids3dShapesGenerator,
        "Greatest Common Factor": GreatestCommonFactorGenerator,
        "Histograms": HistogramsGenerator,
        "Interquartile Range Iqr": InterquartileRangeIqrGenerator,
        "Intro To Absolute Value": IntroToAbsoluteValueGenerator,
        "Intro To Inequalities With Variables": IntroToInequalitiesWithVariablesGenerator,
        "Intro To Negative Numbers": IntroToNegativeNumbersGenerator,
        "Intro To Percents": IntroToPercentsGenerator,
        "Intro To Rates": IntroToRatesGenerator,
        "Intro To Ratios": IntroToRatiosGenerator,
        "Introduction To Khan For Families": IntroductionToKhanForFamiliesGenerator,
        "Least Common Multiple": LeastCommonMultipleGenerator,
        "Mean Absolute Deviation Mad": MeanAbsoluteDeviationMadGenerator,
        "Mean And Median": MeanAndMedianGenerator,
        "Mean And Median Challenge Problems": MeanAndMedianChallengeProblemsGenerator,
        "Meaning Of Exponents": MeaningOfExponentsGenerator,
        "More On Order Of Operations": MoreOnOrderOfOperationsGenerator,
        "Multiplying Decimals": MultiplyingDecimalsGenerator,
        "Negative Numbers Review": NegativeNumbersReviewGenerator,
        "Negative Symbol As Opposite": NegativeSymbolAsOppositeGenerator,
        "Nets Of 3D Figures": NetsOf3dFiguresGenerator,
        "One Step Addition And Subtraction Equations": OneStepAdditionAndSubtractionEquationsGenerator,
        "One Step Equation Word Problems": OneStepEquationWordProblemsGenerator,
        "One Step Equations Intuition": OneStepEquationsIntuitionGenerator,
        "One Step Multiplication And Division Equations": OneStepMultiplicationAndDivisionEquationsGenerator,
        "Order Of Operations Introduction": OrderOfOperationsIntroductionGenerator,
        "Ordering Rational Numbers": OrderingRationalNumbersGenerator,
        "Parts Of Algebraic Expressions": PartsOfAlgebraicExpressionsGenerator,
        "Percent Problems": PercentProblemsGenerator,
        "Percent Word Problems": PercentWordProblemsGenerator,
        "Polygons On Coordinate Plane": PolygonsOnCoordinatePlaneGenerator,
        "Powers Of Fractions And Decimals": PowersOfFractionsAndDecimalsGenerator,
        "Powers Of Whole Numbers": PowersOfWholeNumbersGenerator,
        "Properties Of Numbers": PropertiesOfNumbersGenerator,
        "Ratio Application": RatioApplicationGenerator,
        "Rational Numbers On Number Line": RationalNumbersOnNumberLineGenerator,
        "Ratios Review": RatiosReviewGenerator,
        "Shape Of Data Distributions": ShapeOfDataDistributionsGenerator,
        "Statistical Questions": StatisticalQuestionsGenerator,
        "Substitution And Evaluating Expressions": SubstitutionAndEvaluatingExpressionsGenerator,
        "Subtracting Decimals": SubtractingDecimalsGenerator,
        "Surface Area": SurfaceAreaGenerator,
        "Visualize Equivalent Ratios": VisualizeEquivalentRatiosGenerator,
        "Visualize Percents": VisualizePercentsGenerator,
        "Volume With Fractions": VolumeWithFractionsGenerator,
        "Volume With Mini Cubes": VolumeWithMiniCubesGenerator,
        "Whole Numbers And Integers": WholeNumbersAndIntegersGenerator,
        "Writing Algebraic Expressions Introduction": WritingAlgebraicExpressionsIntroductionGenerator,
        "Writing Basic Algebraic Expressions Word Problems": WritingBasicAlgebraicExpressionsWordProblemsGenerator,
    },
    "K-8 - Grade 7": {
        "Absolute Value Rational Numbers": AbsoluteValueRationalNumbersGenerator,
        "Adding And Subtracting Integers": AddingAndSubtractingIntegersGenerator,
        "Adding And Subtracting Negative Fractions": AddingAndSubtractingNegativeFractionsGenerator,
        "Adding And Subtracting Negatives Variables": AddingAndSubtractingNegativesVariablesGenerator,
        "Adding And Subtracting Rational Numbers": AddingAndSubtractingRationalNumbersGenerator,
        "Adding Negative Numbers Fluently": AddingNegativeNumbersFluentlyGenerator,
        "Addition Subtraction Word Problems Negatives": AdditionSubtractionWordProblemsNegativesGenerator,
        "Area Circumference Challenge": AreaCircumferenceChallengeGenerator,
        "Area Circumference Circles": AreaCircumferenceCirclesGenerator,
        "Basic Probability": BasicProbabilityGenerator,
        "Combining Like Terms": CombiningLikeTermsGenerator,
        "Compare And Interpret Constants": CompareAndInterpretConstantsGenerator,
        "Comparing Sampling Populations": ComparingSamplingPopulationsGenerator,
        "Compound Events Sample Spaces": CompoundEventsSampleSpacesGenerator,
        "Constant Of Proportionality": ConstantOfProportionalityGenerator,
        "Constructing Triangles": ConstructingTrianglesGenerator,
        "Converting Fractions To Decimals": ConvertingFractionsToDecimalsGenerator,
        "Distributive Property Equivalent Expressions": DistributivePropertyEquivalentExpressionsGenerator,
        "Equations Of Proportional Relationships": EquationsOfProportionalRelationshipsGenerator,
        "Graphs Of Proportional Relationships": GraphsOfProportionalRelationshipsGenerator,
        "Identifying Proportional Relationships": IdentifyingProportionalRelationshipsGenerator,
        "Interpreting Linear Expressions": InterpretingLinearExpressionsGenerator,
        "Intro To Adding Negative Numbers": IntroToAddingNegativeNumbersGenerator,
        "Intro To Subtracting Negative Numbers": IntroToSubtractingNegativeNumbersGenerator,
        "Missing Angle Problems": MissingAngleProblemsGenerator,
        "Multiplication Division Word Problems Negatives": MultiplicationDivisionWordProblemsNegativesGenerator,
        "Multiply And Divide Negative Fractions": MultiplyAndDivideNegativeFractionsGenerator,
        "Multiply And Divide Negative Numbers": MultiplyAndDivideNegativeNumbersGenerator,
        "Multiply With Negatives": MultiplyWithNegativesGenerator,
        "One Step Inequalities": OneStepInequalitiesGenerator,
        "Order Of Operations": OrderOfOperationsGenerator,
        "Percent Word Problems": PercentWordProblemsGenerator,
        "Powers With Rational Bases": PowersWithRationalBasesGenerator,
        "Probability Models": ProbabilityModelsGenerator,
        "Properties Of Addition Subtraction": PropertiesOfAdditionSubtractionGenerator,
        "Properties Of Multiplication Division": PropertiesOfMultiplicationDivisionGenerator,
        "Rate Problems With Fractions": RateProblemsWithFractionsGenerator,
        "Rational Number Word Problems": RationalNumberWordProblemsGenerator,
        "Scale Copies": ScaleCopiesGenerator,
        "Scale Drawings": ScaleDrawingsGenerator,
        "Slicing Geometric Shapes": SlicingGeometricShapesGenerator,
        "Subtracting Negative Numbers Fluently": SubtractingNegativeNumbersFluentlyGenerator,
        "Two Step Equation Word Problems": TwoStepEquationWordProblemsGenerator,
        "Two Step Equations Decimals Fractions": TwoStepEquationsDecimalsFractionsGenerator,
        "Two Step Equations Intro": TwoStepEquationsIntroGenerator,
        "Two Step Inequalities": TwoStepInequalitiesGenerator,
        "Understanding Multiplying Dividing Fractions": UnderstandingMultiplyingDividingFractionsGenerator,
        "Vertical Complementary Supplementary Angles": VerticalComplementarySupplementaryAnglesGenerator,
        "Volume Surface Area Word Problems": VolumeSurfaceAreaWordProblemsGenerator,
        "Writing And Solving Proportions": WritingAndSolvingProportionsGenerator,
    },
    "K-8 - Grade 8": {
        "Angles Between Intersecting Lines": AnglesBetweenIntersectingLinesGenerator,
        "Approximating Irrational Numbers": ApproximatingIrrationalNumbersGenerator,
        "Arithmetic With Scientific Notation": ArithmeticWithScientificNotationGenerator,
        "Comparing Linear Functions": ComparingLinearFunctionsGenerator,
        "Congruence And Similarity": CongruenceAndSimilarityGenerator,
        "Constructing Linear Models": ConstructingLinearModelsGenerator,
        "Dilations": DilationsGenerator,
        "Equations With Parentheses": EquationsWithParenthesesGenerator,
        "Equations With Variables On Both Sides": EquationsWithVariablesOnBothSidesGenerator,
        "Equations Word Problems": EquationsWordProblemsGenerator,
        "Estimating Lines Of Best Fit": EstimatingLinesOfBestFitGenerator,
        "Exponent Properties Integer Exponents": ExponentPropertiesIntegerExponentsGenerator,
        "Exponent Properties Intro": ExponentPropertiesIntroGenerator,
        "Exponents With Negative Bases": ExponentsWithNegativeBasesGenerator,
        "Functions": FunctionsGenerator,
        "Graphing Proportional Relationships": GraphingProportionalRelationshipsGenerator,
        "Graphing Slope Intercept Form": GraphingSlopeInterceptFormGenerator,
        "Intercepts": InterceptsGenerator,
        "Interpreting Scatter Plots": InterpretingScatterPlotsGenerator,
        "Intro To Slope Intercept Form": IntroToSlopeInterceptFormGenerator,
        "Intro To Systems Of Equations": IntroToSystemsOfEquationsGenerator,
        "Introduction To Scatter Plots": IntroductionToScatterPlotsGenerator,
        "Irrational Numbers": IrrationalNumbersGenerator,
        "Linear And Nonlinear Functions": LinearAndNonlinearFunctionsGenerator,
        "Linear Models": LinearModelsGenerator,
        "Negative Exponents": NegativeExponentsGenerator,
        "Number Of Solutions To Equations": NumberOfSolutionsToEquationsGenerator,
        "Number Of Solutions To Systems": NumberOfSolutionsToSystemsGenerator,
        "Properties And Definitions Of Transformations": PropertiesAndDefinitionsOfTransformationsGenerator,
        "Pythagorean Theorem": PythagoreanTheoremGenerator,
        "Pythagorean Theorem And Distance": PythagoreanTheoremAndDistanceGenerator,
        "Pythagorean Theorem Application": PythagoreanTheoremApplicationGenerator,
        "Pythagorean Theorem Proofs": PythagoreanTheoremProofsGenerator,
        "Recognizing Functions": RecognizingFunctionsGenerator,
        "Reflections": ReflectionsGenerator,
        "Repeating Decimals": RepeatingDecimalsGenerator,
        "Rotations": RotationsGenerator,
        "Scientific Notation Intro": ScientificNotationIntroGenerator,
        "Scientific Notation Word Problems": ScientificNotationWordProblemsGenerator,
        "Slope": SlopeGenerator,
        "Solutions To Linear Equations": SolutionsToLinearEquationsGenerator,
        "Solving Systems With Substitution": SolvingSystemsWithSubstitutionGenerator,
        "Square And Cube Roots": SquareAndCubeRootsGenerator,
        "Systems Of Equations With Graphing": SystemsOfEquationsWithGraphingGenerator,
        "Systems Of Equations Word Problems": SystemsOfEquationsWordProblemsGenerator,
        "Transformations Intro": TransformationsIntroGenerator,
        "Translations": TranslationsGenerator,
        "Triangle Angles": TriangleAnglesGenerator,
        "Two Way Tables": TwoWayTablesGenerator,
        "Volume": VolumeGenerator,
        "Working With Powers Of 10": WorkingWithPowersOf10Generator,
        "Writing Slope Intercept Equations": WritingSlopeInterceptEquationsGenerator,
    },
    "K-8 - Kindergarten": {
        "Above Below Beside Between": AboveBelowBesideBetweenGenerator,
        "Addition Up To 10": AdditionUpTo10Generator,
        "Addition Up To 5": AdditionUpTo5Generator,
        "Basic Probability": BasicProbabilityGenerator,
        "Circles And Squares": CirclesAndSquaresGenerator,
        "Classifying Objects": ClassifyingObjectsGenerator,
        "Coin Recognition": CoinRecognitionGenerator,
        "Coin Values": CoinValuesGenerator,
        "Comparing Lengths": ComparingLengthsGenerator,
        "Comparing Sizes": ComparingSizesGenerator,
        "Comparing Sizes Measurement": ComparingSizesMeasurementGenerator,
        "Cones And Cylinders": ConesAndCylindersGenerator,
        "Counting Beyond 20": CountingBeyond20Generator,
        "Counting Up To 10": CountingUpTo10Generator,
        "Counting Up To 20": CountingUpTo20Generator,
        "Counting Up To 3": CountingUpTo3Generator,
        "Counting Up To 5": CountingUpTo5Generator,
        "Creating Patterns": CreatingPatternsGenerator,
        "Cubes And Spheres": CubesAndSpheresGenerator,
        "Days And Weeks": DaysAndWeeksGenerator,
        "Equal Quantities": EqualQuantitiesGenerator,
        "Extending Patterns": ExtendingPatternsGenerator,
        "Left Right Inside Outside": LeftRightInsideOutsideGenerator,
        "More And Less": MoreAndLessGenerator,
        "Ordering Objects": OrderingObjectsGenerator,
        "Reading Clocks Introduction": ReadingClocksIntroductionGenerator,
        "Reading Simple Graphs": ReadingSimpleGraphsGenerator,
        "Recognizing Patterns": RecognizingPatternsGenerator,
        "Seasons": SeasonsGenerator,
        "Sorting Objects": SortingObjectsGenerator,
        "Subtraction Up To 10": SubtractionUpTo10Generator,
        "Subtraction Up To 5": SubtractionUpTo5Generator,
        "Triangles And Rectangles": TrianglesAndRectanglesGenerator,
    },
}
